/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all AgentRuntimes */
        get: operations["listAgents"];
        put?: never;
        /** Create a new AgentRuntime */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific AgentRuntime */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{namespace}/{name}/scale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Scale an AgentRuntime */
        put: operations["scaleAgent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{namespace}/{name}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get logs from an agent's pods */
        get: operations["getAgentLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/promptpacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all PromptPacks */
        get: operations["listPromptPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/promptpacks/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific PromptPack */
        get: operations["getPromptPack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/toolregistries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all ToolRegistries */
        get: operations["listToolRegistries"];
        put?: never;
        /** Create a new ToolRegistry */
        post: operations["createToolRegistry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/toolregistries/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific ToolRegistry */
        get: operations["getToolRegistry"];
        /** Update a ToolRegistry */
        put: operations["updateToolRegistry"];
        post?: never;
        /** Delete a ToolRegistry */
        delete: operations["deleteToolRegistry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all Providers */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific Provider */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agentpolicies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all AgentPolicies */
        get: operations["listAgentPolicies"];
        put?: never;
        /** Create a new AgentPolicy */
        post: operations["createAgentPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agentpolicies/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific AgentPolicy */
        get: operations["getAgentPolicy"];
        /** Update an AgentPolicy */
        put: operations["updateAgentPolicy"];
        post?: never;
        /** Delete an AgentPolicy */
        delete: operations["deleteAgentPolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/toolpolicies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all ToolPolicies */
        get: operations["listToolPolicies"];
        put?: never;
        /** Create a new ToolPolicy */
        post: operations["createToolPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/toolpolicies/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific ToolPolicy */
        get: operations["getToolPolicy"];
        /** Update a ToolPolicy */
        put: operations["updateToolPolicy"];
        post?: never;
        /** Delete a ToolPolicy */
        delete: operations["deleteToolPolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated statistics */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all namespaces */
        get: operations["listNamespaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        ScaleRequest: {
            /** @description Desired number of replicas */
            replicas: number;
        };
        LogEntry: {
            /** Format: date-time */
            timestamp?: string;
            /** @enum {string} */
            level?: "info" | "warn" | "error" | "debug";
            message?: string;
            container?: string;
        };
        ObjectMeta: {
            name?: string;
            namespace?: string;
            uid?: string;
            resourceVersion?: string;
            /** Format: date-time */
            creationTimestamp?: string;
            labels?: {
                [key: string]: string;
            };
            annotations?: {
                [key: string]: string;
            };
        };
        AgentRuntime: {
            apiVersion?: string;
            kind?: string;
            metadata?: components["schemas"]["ObjectMeta"];
            spec?: components["schemas"]["AgentRuntimeSpec"];
            status?: components["schemas"]["AgentRuntimeStatus"];
        };
        AgentRuntimeSpec: {
            promptPackRef?: components["schemas"]["LocalObjectReference"];
            toolRegistryRef?: components["schemas"]["LocalObjectReference"];
            providers?: components["schemas"]["NamedProviderRef"][];
            facade?: components["schemas"]["FacadeConfig"];
            session?: components["schemas"]["SessionConfig"];
            runtime?: components["schemas"]["RuntimeConfig"];
            console?: components["schemas"]["ConsoleConfig"];
        };
        LocalObjectReference: {
            name?: string;
            namespace?: string;
        };
        NamedProviderRef: {
            name: string;
            providerRef: components["schemas"]["LocalObjectReference"];
        };
        FacadeConfig: {
            /** @enum {string} */
            type?: "websocket" | "grpc";
            port?: number;
            handler?: string;
        };
        SessionConfig: {
            /** @enum {string} */
            type?: "memory" | "redis";
            ttl?: string;
            storeRef?: components["schemas"]["LocalObjectReference"];
        };
        RuntimeConfig: {
            replicas?: number;
            resources?: components["schemas"]["ResourceRequirements"];
            autoscaling?: components["schemas"]["AutoscalingConfig"];
        };
        ResourceRequirements: {
            requests?: {
                [key: string]: string;
            };
            limits?: {
                [key: string]: string;
            };
        };
        AutoscalingConfig: {
            enabled?: boolean;
            /** @enum {string} */
            type?: "hpa" | "keda";
            minReplicas?: number;
            maxReplicas?: number;
        };
        /** @description Configuration for dashboard console UI */
        ConsoleConfig: {
            /** @description MIME types allowed for file uploads (e.g., "image/*", "application/pdf") */
            allowedAttachmentTypes?: string[];
            /** @description File extensions as fallback (e.g., ".png", ".pdf") */
            allowedExtensions?: string[];
            /**
             * Format: int64
             * @description Maximum file size in bytes
             * @default 10485760
             */
            maxFileSize: number;
            /**
             * @description Maximum number of files per message
             * @default 5
             */
            maxFiles: number;
            mediaRequirements?: components["schemas"]["MediaRequirements"];
        };
        /** @description Width and height in pixels */
        Dimensions: {
            /** @description Width in pixels */
            width: number;
            /** @description Height in pixels */
            height: number;
        };
        /** @description Requirements for image media */
        ImageRequirements: {
            /**
             * Format: int64
             * @description Maximum file size in bytes for images
             */
            maxSizeBytes?: number;
            maxDimensions?: components["schemas"]["Dimensions"];
            recommendedDimensions?: components["schemas"]["Dimensions"];
            /** @description Supported image formats (e.g., "png", "jpeg", "gif", "webp") */
            supportedFormats?: string[];
            /** @description Preferred format for best results */
            preferredFormat?: string;
            /**
             * @description Guidance on image compression
             * @enum {string}
             */
            compressionGuidance?: "none" | "lossless" | "lossy-high" | "lossy-medium" | "lossy-low";
        };
        /** @description Requirements for video media */
        VideoRequirements: {
            /** @description Maximum video duration in seconds */
            maxDurationSeconds?: number;
            /** @description Whether segment selection is supported */
            supportsSegmentSelection?: boolean;
            /**
             * @description How video is processed
             * @enum {string}
             */
            processingMode?: "frames" | "transcription" | "both" | "native";
            /** @description Interval in seconds between extracted frames */
            frameExtractionInterval?: number;
        };
        /** @description Requirements for audio media */
        AudioRequirements: {
            /** @description Maximum audio duration in seconds */
            maxDurationSeconds?: number;
            /** @description Recommended sample rate in Hz */
            recommendedSampleRate?: number;
            /** @description Whether segment selection is supported */
            supportsSegmentSelection?: boolean;
        };
        /** @description Requirements for document media */
        DocumentRequirements: {
            /** @description Maximum number of pages */
            maxPages?: number;
            /** @description Whether OCR is supported for scanned documents */
            supportsOCR?: boolean;
        };
        /** @description Provider-specific requirements for different media types */
        MediaRequirements: {
            image?: components["schemas"]["ImageRequirements"];
            video?: components["schemas"]["VideoRequirements"];
            audio?: components["schemas"]["AudioRequirements"];
            document?: components["schemas"]["DocumentRequirements"];
        };
        AgentRuntimeStatus: {
            /** @enum {string} */
            phase?: "Pending" | "Running" | "Failed";
            conditions?: components["schemas"]["Condition"][];
            readyReplicas?: number;
            replicas?: number;
            /** @description Internal Kubernetes service endpoint for agent facade (e.g., my-agent.default.svc.cluster.local:8080) */
            serviceEndpoint?: string;
        };
        Condition: {
            type?: string;
            /** @enum {string} */
            status?: "True" | "False" | "Unknown";
            /** Format: date-time */
            lastTransitionTime?: string;
            reason?: string;
            message?: string;
        };
        PromptPack: {
            apiVersion?: string;
            kind?: string;
            metadata?: components["schemas"]["ObjectMeta"];
            spec?: components["schemas"]["PromptPackSpec"];
            status?: components["schemas"]["PromptPackStatus"];
        };
        PromptPackSpec: {
            version?: string;
            source?: components["schemas"]["PromptPackSource"];
            rollout?: components["schemas"]["RolloutConfig"];
        };
        PromptPackSource: {
            /** @enum {string} */
            type?: "configmap" | "git";
            configMapRef?: components["schemas"]["LocalObjectReference"];
            gitRef?: components["schemas"]["GitSource"];
        };
        GitSource: {
            url?: string;
            ref?: string;
            path?: string;
        };
        RolloutConfig: {
            /** @enum {string} */
            type?: "immediate" | "canary";
            canaryWeight?: number;
        };
        PromptPackStatus: {
            /** @enum {string} */
            phase?: "Pending" | "Active" | "Canary" | "Failed";
            conditions?: components["schemas"]["Condition"][];
            activeVersion?: string;
            canaryVersion?: string;
        };
        ToolRegistry: {
            apiVersion?: string;
            kind?: string;
            metadata?: components["schemas"]["ObjectMeta"];
            spec?: components["schemas"]["ToolRegistrySpec"];
            status?: components["schemas"]["ToolRegistryStatus"];
        };
        ToolRegistrySpec: {
            tools?: components["schemas"]["ToolDefinition"][];
            selector?: components["schemas"]["ServiceSelector"];
        };
        ToolDefinition: {
            name?: string;
            description?: string;
            /** @enum {string} */
            type?: "http" | "grpc" | "mcp";
            url?: string;
            inputSchema?: {
                [key: string]: unknown;
            };
        };
        ServiceSelector: {
            matchLabels?: {
                [key: string]: string;
            };
        };
        ToolRegistryStatus: {
            /** @enum {string} */
            phase?: "Pending" | "Ready" | "Degraded" | "Failed";
            conditions?: components["schemas"]["Condition"][];
            discoveredToolsCount?: number;
            discoveredTools?: components["schemas"]["DiscoveredTool"][];
        };
        DiscoveredTool: {
            name?: string;
            endpoint?: string;
            /** @enum {string} */
            status?: "Available" | "Unavailable";
        };
        Provider: {
            apiVersion?: string;
            kind?: string;
            metadata?: components["schemas"]["ObjectMeta"];
            spec?: components["schemas"]["ProviderSpec"];
            status?: components["schemas"]["ProviderStatus"];
        };
        ProviderSpec: {
            /** @enum {string} */
            type?: "claude" | "openai" | "gemini" | "ollama" | "mock";
            model?: string;
            /** @description Override the provider's default API endpoint */
            baseURL?: string;
            secretRef?: components["schemas"]["SecretKeyRef"];
            defaults?: components["schemas"]["ProviderDefaults"];
            pricing?: components["schemas"]["ProviderPricing"];
            /** @description Enable credential validation on reconciliation */
            validateCredentials?: boolean;
        };
        SecretKeyRef: {
            name: string;
            key?: string;
        };
        ProviderDefaults: {
            temperature?: string;
            topP?: string;
            maxTokens?: number;
            contextWindow?: number;
            /** @enum {string} */
            truncationStrategy?: "sliding" | "summarize" | "custom";
        };
        ProviderPricing: {
            inputCostPer1K?: string;
            outputCostPer1K?: string;
            cachedCostPer1K?: string;
        };
        ProviderStatus: {
            /** @enum {string} */
            phase?: "Ready" | "Error";
            conditions?: components["schemas"]["Condition"][];
            /** Format: date-time */
            lastValidatedAt?: string;
            observedGeneration?: number;
        };
        AgentPolicy: {
            apiVersion?: string;
            kind?: string;
            metadata?: components["schemas"]["ObjectMeta"];
            spec?: components["schemas"]["AgentPolicySpec"];
            status?: components["schemas"]["AgentPolicyStatus"];
        };
        AgentPolicySpec: {
            selector?: {
                agents?: string[];
            };
            claimMapping?: {
                forwardClaims?: {
                    claim: string;
                    header: string;
                }[];
            };
            toolAccess?: {
                /** @enum {string} */
                mode?: "allowlist" | "denylist";
                rules?: {
                    registry: string;
                    tools: string[];
                }[];
            };
            /**
             * @default enforce
             * @enum {string}
             */
            mode: "enforce" | "permissive";
            /**
             * @default deny
             * @enum {string}
             */
            onFailure: "deny" | "allow";
        };
        AgentPolicyStatus: {
            /** @enum {string} */
            phase?: "Active" | "Error";
            matchedAgents?: number;
            conditions?: components["schemas"]["Condition"][];
            observedGeneration?: number;
        };
        ToolPolicy: {
            apiVersion?: string;
            kind?: string;
            metadata?: components["schemas"]["ObjectMeta"];
            spec?: components["schemas"]["ToolPolicySpec"];
            status?: components["schemas"]["ToolPolicyStatus"];
        };
        ToolPolicySpec: {
            selector: {
                registry: string;
                tools?: string[];
            };
            rules: {
                name: string;
                description?: string;
                deny: {
                    cel: string;
                    message: string;
                };
            }[];
            requiredClaims?: {
                claim: string;
                message: string;
            }[];
            /**
             * @default enforce
             * @enum {string}
             */
            mode: "enforce" | "audit";
            /**
             * @default deny
             * @enum {string}
             */
            onFailure: "deny" | "allow";
            headerInjection?: {
                header: string;
                value?: string;
                cel?: string;
            }[];
            audit?: {
                logDecisions?: boolean;
                redactFields?: string[];
            };
        };
        ToolPolicyStatus: {
            /** @enum {string} */
            phase?: "Active" | "Error";
            conditions?: components["schemas"]["Condition"][];
            observedGeneration?: number;
            ruleCount?: number;
        };
        Stats: {
            agents?: {
                total?: number;
                running?: number;
                pending?: number;
                failed?: number;
            };
            promptPacks?: {
                total?: number;
                active?: number;
                canary?: number;
            };
            tools?: {
                total?: number;
                available?: number;
                degraded?: number;
            };
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bad request - invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: {
                /** @description Filter by namespace */
                namespace?: string;
                /** @description Kubernetes label selector for filtering */
                labelSelector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRuntime"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRuntime"];
            };
        };
        responses: {
            /** @description Agent created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRuntime"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Agent already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRuntime"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    scaleAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScaleRequest"];
            };
        };
        responses: {
            /** @description Agent scaled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRuntime"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getAgentLogs: {
        parameters: {
            query?: {
                /** @description Number of lines to return from the end of logs */
                tailLines?: number;
                /** @description Return logs from the last N seconds */
                sinceSeconds?: number;
                /** @description Filter logs by container name */
                container?: string;
            };
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listPromptPacks: {
        parameters: {
            query?: {
                /** @description Filter by namespace */
                namespace?: string;
                /** @description Kubernetes label selector for filtering */
                labelSelector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of prompt packs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPack"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getPromptPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PromptPack details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPack"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listToolRegistries: {
        parameters: {
            query?: {
                /** @description Filter by namespace */
                namespace?: string;
                /** @description Kubernetes label selector for filtering */
                labelSelector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tool registries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolRegistry"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createToolRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRegistry"];
            };
        };
        responses: {
            /** @description ToolRegistry created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolRegistry"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description ToolRegistry already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getToolRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ToolRegistry details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolRegistry"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateToolRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRegistry"];
            };
        };
        responses: {
            /** @description ToolRegistry updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolRegistry"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteToolRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ToolRegistry deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listProviders: {
        parameters: {
            query?: {
                /** @description Filter by namespace */
                namespace?: string;
                /** @description Kubernetes label selector for filtering */
                labelSelector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAgentPolicies: {
        parameters: {
            query?: {
                /** @description Filter by namespace */
                namespace?: string;
                /** @description Kubernetes label selector for filtering */
                labelSelector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of agent policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPolicy"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAgentPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPolicy"];
            };
        };
        responses: {
            /** @description AgentPolicy created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getAgentPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AgentPolicy details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPolicy"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateAgentPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPolicy"];
            };
        };
        responses: {
            /** @description AgentPolicy updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAgentPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AgentPolicy deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listToolPolicies: {
        parameters: {
            query?: {
                /** @description Filter by namespace */
                namespace?: string;
                /** @description Kubernetes label selector for filtering */
                labelSelector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tool policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolPolicy"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createToolPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolPolicy"];
            };
        };
        responses: {
            /** @description ToolPolicy created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getToolPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ToolPolicy details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolPolicy"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateToolPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolPolicy"];
            };
        };
        responses: {
            /** @description ToolPolicy updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteToolPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ToolPolicy deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listNamespaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of namespace names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
