/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package tools

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// ToolConfig represents the tools configuration file format.
// The new format uses Handlers; Tools is kept for backward compatibility.
type ToolConfig struct {
	// Handlers is the new handler-based configuration (generated by operator).
	Handlers []HandlerEntry `json:"handlers,omitempty" yaml:"handlers,omitempty"`

	// Tools is the legacy tool-based configuration (deprecated).
	// Kept for backward compatibility during migration.
	Tools []ToolEntry `json:"tools,omitempty" yaml:"tools,omitempty"`
}

// HandlerEntry represents a single handler in the config.
// Handlers can expose one or more tools. Self-describing handlers (MCP, OpenAPI)
// discover tools at runtime, while explicit handlers (HTTP, gRPC) require a tool definition.
type HandlerEntry struct {
	Name          string      `json:"name" yaml:"name"`
	Type          string      `json:"type" yaml:"type"`
	Endpoint      string      `json:"endpoint" yaml:"endpoint"`
	Tool          *ToolDefCfg `json:"tool,omitempty" yaml:"tool,omitempty"` // For http/grpc handlers
	HTTPConfig    *HTTPCfg    `json:"httpConfig,omitempty" yaml:"httpConfig,omitempty"`
	GRPCConfig    *GRPCCfg    `json:"grpcConfig,omitempty" yaml:"grpcConfig,omitempty"`
	MCPConfig     *MCPCfg     `json:"mcpConfig,omitempty" yaml:"mcpConfig,omitempty"`
	OpenAPIConfig *OpenAPICfg `json:"openAPIConfig,omitempty" yaml:"openAPIConfig,omitempty"`
	Timeout       string      `json:"timeout,omitempty" yaml:"timeout,omitempty"`
	Retries       int32       `json:"retries,omitempty" yaml:"retries,omitempty"`
}

// ToolDefCfg represents a tool definition for explicit handlers (HTTP, gRPC).
type ToolDefCfg struct {
	Name         string      `json:"name" yaml:"name"`
	Description  string      `json:"description" yaml:"description"`
	InputSchema  interface{} `json:"inputSchema" yaml:"inputSchema"`
	OutputSchema interface{} `json:"outputSchema,omitempty" yaml:"outputSchema,omitempty"`
}

// ToolEntry represents a single tool in the legacy config format.
// Deprecated: Use HandlerEntry instead.
type ToolEntry struct {
	Name          string      `json:"name" yaml:"name"`
	Type          string      `json:"type" yaml:"type"`
	Description   string      `json:"description,omitempty" yaml:"description,omitempty"`
	HTTPConfig    *HTTPCfg    `json:"httpConfig,omitempty" yaml:"httpConfig,omitempty"`
	GRPCConfig    *GRPCCfg    `json:"grpcConfig,omitempty" yaml:"grpcConfig,omitempty"`
	MCPConfig     *MCPCfg     `json:"mcpConfig,omitempty" yaml:"mcpConfig,omitempty"`
	OpenAPIConfig *OpenAPICfg `json:"openAPIConfig,omitempty" yaml:"openAPIConfig,omitempty"`
	Timeout       string      `json:"timeout,omitempty" yaml:"timeout,omitempty"`
	Retries       int32       `json:"retries,omitempty" yaml:"retries,omitempty"`
}

// HTTPCfg represents HTTP configuration for a tool.
type HTTPCfg struct {
	Endpoint    string            `json:"endpoint" yaml:"endpoint"`
	Method      string            `json:"method,omitempty" yaml:"method,omitempty"`
	Headers     map[string]string `json:"headers,omitempty" yaml:"headers,omitempty"`
	ContentType string            `json:"contentType,omitempty" yaml:"contentType,omitempty"`
	AuthType    string            `json:"authType,omitempty" yaml:"authType,omitempty"`
	AuthToken   string            `json:"authToken,omitempty" yaml:"authToken,omitempty"`
}

// GRPCCfg represents gRPC configuration for a tool.
type GRPCCfg struct {
	Endpoint              string `json:"endpoint" yaml:"endpoint"`
	TLS                   bool   `json:"tls,omitempty" yaml:"tls,omitempty"`
	TLSCertPath           string `json:"tlsCertPath,omitempty" yaml:"tlsCertPath,omitempty"`
	TLSKeyPath            string `json:"tlsKeyPath,omitempty" yaml:"tlsKeyPath,omitempty"`
	TLSCAPath             string `json:"tlsCAPath,omitempty" yaml:"tlsCAPath,omitempty"`
	TLSInsecureSkipVerify bool   `json:"tlsInsecureSkipVerify,omitempty" yaml:"tlsInsecureSkipVerify,omitempty"`
}

// MCPCfg represents MCP configuration for a tool.
type MCPCfg struct {
	Transport string            `json:"transport" yaml:"transport"`
	Endpoint  string            `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`
	Command   string            `json:"command,omitempty" yaml:"command,omitempty"`
	Args      []string          `json:"args,omitempty" yaml:"args,omitempty"`
	WorkDir   string            `json:"workDir,omitempty" yaml:"workDir,omitempty"`
	Env       map[string]string `json:"env,omitempty" yaml:"env,omitempty"`
}

// OpenAPICfg represents OpenAPI configuration for a tool.
type OpenAPICfg struct {
	SpecURL         string            `json:"specURL" yaml:"specURL"`
	BaseURL         string            `json:"baseURL,omitempty" yaml:"baseURL,omitempty"`
	OperationFilter []string          `json:"operationFilter,omitempty" yaml:"operationFilter,omitempty"`
	Headers         map[string]string `json:"headers,omitempty" yaml:"headers,omitempty"`
	AuthType        string            `json:"authType,omitempty" yaml:"authType,omitempty"`
	AuthToken       string            `json:"authToken,omitempty" yaml:"authToken,omitempty"`
}

// LoadConfig loads tool configuration from a YAML file.
func LoadConfig(path string) (*ToolConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	var config ToolConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to parse config: %w", err)
	}

	return &config, nil
}

// ToolTypeHTTP is the HTTP tool type.
const ToolTypeHTTP = "http"

// ToolTypeGRPC is the gRPC tool type.
const ToolTypeGRPC = "grpc"

// ToolTypeMCP is the MCP tool type.
const ToolTypeMCP = "mcp"

// ToolTypeOpenAPI is the OpenAPI tool type.
const ToolTypeOpenAPI = "openapi"
