// Copyright 2024 Altaira Labs
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: api/proto/runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolExecution indicates where a tool is executed.
type ToolExecution int32

const (
	// TOOL_EXECUTION_SERVER means the tool runs server-side in the runtime.
	ToolExecution_TOOL_EXECUTION_SERVER ToolExecution = 0
	// TOOL_EXECUTION_CLIENT means the tool must be fulfilled by the client.
	ToolExecution_TOOL_EXECUTION_CLIENT ToolExecution = 1
)

// Enum value maps for ToolExecution.
var (
	ToolExecution_name = map[int32]string{
		0: "TOOL_EXECUTION_SERVER",
		1: "TOOL_EXECUTION_CLIENT",
	}
	ToolExecution_value = map[string]int32{
		"TOOL_EXECUTION_SERVER": 0,
		"TOOL_EXECUTION_CLIENT": 1,
	}
)

func (x ToolExecution) Enum() *ToolExecution {
	p := new(ToolExecution)
	*p = x
	return p
}

func (x ToolExecution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolExecution) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_runtime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (ToolExecution) Type() protoreflect.EnumType {
	return &file_api_proto_runtime_v1_runtime_proto_enumTypes[0]
}

func (x ToolExecution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolExecution.Descriptor instead.
func (ToolExecution) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

// ResumeState is the disposition of a session's working context.
//
// The three states exist because the facade must act differently on each: a
// missing conversation is a client-visible expiry, whereas an unreachable
// store is a server fault. Collapsing them would recreate the bug this RPC
// exists to fix — telling a client its session expired when in fact the
// context is intact and the store was merely briefly unreachable.
type ResumeState int32

const (
	// Unset. Treated as RESUME_STATE_UNAVAILABLE by callers.
	ResumeState_RESUME_STATE_UNSPECIFIED ResumeState = 0
	// Context is present; sdk.Resume will succeed.
	ResumeState_RESUME_STATE_RESUMABLE ResumeState = 1
	// Store answered definitively that no context exists for this id — it
	// expired, or was never persisted. The session cannot be continued.
	ResumeState_RESUME_STATE_NOT_FOUND ResumeState = 2
	// The store could not be consulted (unreachable, timed out, or no store is
	// configured). Resumability is unknown; this is NOT an expiry.
	ResumeState_RESUME_STATE_UNAVAILABLE ResumeState = 3
)

// Enum value maps for ResumeState.
var (
	ResumeState_name = map[int32]string{
		0: "RESUME_STATE_UNSPECIFIED",
		1: "RESUME_STATE_RESUMABLE",
		2: "RESUME_STATE_NOT_FOUND",
		3: "RESUME_STATE_UNAVAILABLE",
	}
	ResumeState_value = map[string]int32{
		"RESUME_STATE_UNSPECIFIED": 0,
		"RESUME_STATE_RESUMABLE":   1,
		"RESUME_STATE_NOT_FOUND":   2,
		"RESUME_STATE_UNAVAILABLE": 3,
	}
)

func (x ResumeState) Enum() *ResumeState {
	p := new(ResumeState)
	*p = x
	return p
}

func (x ResumeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResumeState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_runtime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (ResumeState) Type() protoreflect.EnumType {
	return &file_api_proto_runtime_v1_runtime_proto_enumTypes[1]
}

func (x ResumeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResumeState.Descriptor instead.
func (ResumeState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

// ClientMessage represents a message from the client to the runtime.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id identifies the conversation session for state management.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// content is the user's message text (legacy, for backward compatibility).
	// For multimodal messages, use the parts field instead.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// metadata contains optional key-value pairs for additional context.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// parts contains multimodal content parts (text, images, audio, video, files).
	// If non-empty, this takes precedence over the content field.
	Parts []*ContentPart `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	// client_tool_result carries the result of a client-side tool execution.
	// Set when responding to a ToolCall with execution=CLIENT.
	ClientToolResult *ClientToolResult `protobuf:"bytes,5,opt,name=client_tool_result,json=clientToolResult,proto3" json:"client_tool_result,omitempty"`
	// consent_grants carries per-message consent category grants from the client.
	// When present, these override stored consent for this request.
	ConsentGrants []string `protobuf:"bytes,6,rep,name=consent_grants,json=consentGrants,proto3" json:"consent_grants,omitempty"`
	// duplex_start, when set on the first message of a Converse stream, switches
	// the stream into bidirectional audio mode (OSS duplex transport).
	DuplexStart *DuplexStart `protobuf:"bytes,7,opt,name=duplex_start,json=duplexStart,proto3" json:"duplex_start,omitempty"`
	// audio_input carries one inbound audio frame during a duplex session.
	AudioInput    *AudioInputChunk `protobuf:"bytes,8,opt,name=audio_input,json=audioInput,proto3" json:"audio_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ClientMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClientMessage) GetParts() []*ContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *ClientMessage) GetClientToolResult() *ClientToolResult {
	if x != nil {
		return x.ClientToolResult
	}
	return nil
}

func (x *ClientMessage) GetConsentGrants() []string {
	if x != nil {
		return x.ConsentGrants
	}
	return nil
}

func (x *ClientMessage) GetDuplexStart() *DuplexStart {
	if x != nil {
		return x.DuplexStart
	}
	return nil
}

func (x *ClientMessage) GetAudioInput() *AudioInputChunk {
	if x != nil {
		return x.AudioInput
	}
	return nil
}

// ClientToolResult carries the client's response to a client-side tool call.
type ClientToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// call_id matches the ToolCall.id that this result is for.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// result_json contains the tool result as a JSON string.
	ResultJson string `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// is_rejected indicates the client rejected the tool call.
	IsRejected bool `protobuf:"varint,3,opt,name=is_rejected,json=isRejected,proto3" json:"is_rejected,omitempty"`
	// rejection_reason explains why the client rejected the tool call.
	RejectionReason string `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientToolResult) Reset() {
	*x = ClientToolResult{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToolResult) ProtoMessage() {}

func (x *ClientToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToolResult.ProtoReflect.Descriptor instead.
func (*ClientToolResult) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ClientToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ClientToolResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ClientToolResult) GetIsRejected() bool {
	if x != nil {
		return x.IsRejected
	}
	return false
}

func (x *ClientToolResult) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

// ServerMessage represents a message from the runtime to the client.
// Uses oneof to ensure only one message type is sent at a time.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Chunk
	//	*ServerMessage_ToolCall
	//	*ServerMessage_Done
	//	*ServerMessage_Error
	//	*ServerMessage_MediaChunk
	//	*ServerMessage_Interruption
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetChunk() *Chunk {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ServerMessage) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ServerMessage) GetDone() *Done {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetMediaChunk() *MediaChunk {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_MediaChunk); ok {
			return x.MediaChunk
		}
	}
	return nil
}

func (x *ServerMessage) GetInterruption() *Interruption {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Interruption); ok {
			return x.Interruption
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Chunk struct {
	// chunk contains a partial text response for streaming.
	Chunk *Chunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type ServerMessage_ToolCall struct {
	// tool_call notifies the facade of a client-side tool invocation.
	// The facade forwards this to the WebSocket client, which must respond
	// with a ClientToolResult before the conversation can continue.
	// Server-side tool calls are handled internally by the runtime and
	// are not sent on this stream.
	ToolCall *ToolCall `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ServerMessage_Done struct {
	// done signals the completion of a response.
	Done *Done `protobuf:"bytes,4,opt,name=done,proto3,oneof"`
}

type ServerMessage_Error struct {
	// error indicates an error occurred during processing.
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type ServerMessage_MediaChunk struct {
	// media_chunk contains a streaming media chunk (image, audio, video).
	// Sent during streaming when the LLM produces media content, allowing
	// the client to begin processing before the entire media is available.
	MediaChunk *MediaChunk `protobuf:"bytes,6,opt,name=media_chunk,json=mediaChunk,proto3,oneof"`
}

type ServerMessage_Interruption struct {
	// interruption signals a barge-in; the client clears buffered audio.
	Interruption *Interruption `protobuf:"bytes,7,opt,name=interruption,proto3,oneof"`
}

func (*ServerMessage_Chunk) isServerMessage_Message() {}

func (*ServerMessage_ToolCall) isServerMessage_Message() {}

func (*ServerMessage_Done) isServerMessage_Message() {}

func (*ServerMessage_Error) isServerMessage_Message() {}

func (*ServerMessage_MediaChunk) isServerMessage_Message() {}

func (*ServerMessage_Interruption) isServerMessage_Message() {}

// Chunk contains a partial text response for streaming output.
type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content is the text chunk to append to the response.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ToolCall represents a tool invocation.
// For server-side tools this is informational (UI display only).
// For client-side tools the client must send back a ClientToolResult.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique identifier for this tool call.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the name of the tool being called.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// arguments_json contains the tool arguments as a JSON string.
	ArgumentsJson string `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// execution indicates whether this tool runs server-side or client-side.
	Execution ToolExecution `protobuf:"varint,4,opt,name=execution,proto3,enum=omnia.runtime.v1.ToolExecution" json:"execution,omitempty"`
	// consent_message is a human-readable consent prompt for client-side tools.
	ConsentMessage string `protobuf:"bytes,5,opt,name=consent_message,json=consentMessage,proto3" json:"consent_message,omitempty"`
	// categories are semantic consent categories (e.g., "location", "filesystem").
	Categories    []string `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolCall) GetExecution() ToolExecution {
	if x != nil {
		return x.Execution
	}
	return ToolExecution_TOOL_EXECUTION_SERVER
}

func (x *ToolCall) GetConsentMessage() string {
	if x != nil {
		return x.ConsentMessage
	}
	return ""
}

func (x *ToolCall) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

// ToolResult contains the result of a tool execution (informational for UI display).
type ToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id matches the corresponding ToolCall id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// result_json contains the tool result as a JSON string.
	ResultJson string `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// is_error indicates whether the tool execution failed.
	IsError       bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ToolResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// Done signals the completion of a conversation turn.
type Done struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// final_content contains the complete response text (optional).
	// For text-only responses, this contains the full response.
	// For multimodal responses, use the parts field instead.
	FinalContent string `protobuf:"bytes,1,opt,name=final_content,json=finalContent,proto3" json:"final_content,omitempty"`
	// usage contains token usage statistics for this turn.
	Usage *Usage `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	// parts contains multimodal content parts (text, images, audio, video).
	// If non-empty, this takes precedence over final_content for rich responses.
	Parts         []*ContentPart `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *Done) GetFinalContent() string {
	if x != nil {
		return x.FinalContent
	}
	return ""
}

func (x *Done) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Done) GetParts() []*ContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// ContentPart represents a single piece of content in a multimodal message.
type ContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type indicates the content type: "text", "image", "audio", "video"
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// text contains text content (only set when type="text")
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// media contains media content (only set when type="image", "audio", or "video")
	Media         *MediaContent `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *ContentPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContentPart) GetMedia() *MediaContent {
	if x != nil {
		return x.Media
	}
	return nil
}

// MediaContent represents media data (image, audio, video) in a message.
type MediaContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data contains base64-encoded media data (for resolved file:// and mock:// URLs)
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// url contains the media URL (for http:// and https:// URLs that are passed through)
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// mime_type indicates the media format (e.g., "image/png", "audio/mp3")
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// storage_ref is an opaque backend storage reference (e.g. "omnia://sessions/{id}/media/{mediaID}").
	// When set, the runtime resolves it to media bytes at provider-call time via the injected media store.
	StorageRef    string `protobuf:"bytes,4,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaContent) Reset() {
	*x = MediaContent{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaContent) ProtoMessage() {}

func (x *MediaContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaContent.ProtoReflect.Descriptor instead.
func (*MediaContent) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *MediaContent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MediaContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaContent) GetStorageRef() string {
	if x != nil {
		return x.StorageRef
	}
	return ""
}

// Usage contains token usage and cost information.
type Usage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// input_tokens is the number of tokens in the input/prompt.
	InputTokens int32 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	// output_tokens is the number of tokens in the output/response.
	OutputTokens int32 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	// cost_usd is the estimated cost in USD for this request.
	CostUsd       float32 `protobuf:"fixed32,3,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCostUsd() float32 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

// Error represents an error that occurred during processing.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is a machine-readable error code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// message is a human-readable error description.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Interruption signals that the in-flight response was interrupted (e.g. the
// user started speaking over the agent during a duplex session). The client
// must clear any buffered audio playback immediately.
type Interruption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interruption) Reset() {
	*x = Interruption{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interruption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interruption) ProtoMessage() {}

func (x *Interruption) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interruption.ProtoReflect.Descriptor instead.
func (*Interruption) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

// MediaChunk contains a streaming media chunk for progressive media delivery.
// All chunks sharing the same media_id belong to the same media stream.
type MediaChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// media_id is the unique identifier for this media stream.
	MediaId string `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	// sequence is the 0-indexed sequence number for ordering chunks.
	Sequence int32 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// is_last indicates this is the final chunk for this media stream.
	IsLast bool `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	// mime_type indicates the media format (e.g., "image/png", "audio/mp3").
	MimeType string `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// data contains raw media bytes (avoids base64 overhead in gRPC path).
	Data          []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaChunk) Reset() {
	*x = MediaChunk{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaChunk) ProtoMessage() {}

func (x *MediaChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaChunk.ProtoReflect.Descriptor instead.
func (*MediaChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *MediaChunk) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaChunk) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MediaChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *MediaChunk) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// InvocationRequest carries a Function call from the facade.
type InvocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// input_json is the raw JSON payload submitted by the caller. The facade
	// has already validated this against AgentRuntime.spec.inputSchema; the
	// runtime treats it as an opaque user message body.
	InputJson string `protobuf:"bytes,1,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	// invocation_id is a UUID for this Function call, used for log and
	// trace correlation. Assigned by the facade.
	InvocationId string `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// metadata carries optional key-value context (caller identity, auth
	// subject, custom headers). Not interpreted by the runtime.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationRequest) Reset() {
	*x = InvocationRequest{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationRequest) ProtoMessage() {}

func (x *InvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationRequest.ProtoReflect.Descriptor instead.
func (*InvocationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *InvocationRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *InvocationRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvocationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InvocationResponse carries the runtime's reply to the facade. On
// success the facade then validates output_json against
// AgentRuntime.spec.outputSchema before returning to the HTTP caller.
type InvocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// output_json is the raw assistant text. The facade validates it
	// against the output schema; if invalid, the facade returns HTTP 502
	// with this raw payload in the response body (per Q2 lock on #1103).
	OutputJson string `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	// usage contains token + cost statistics for the call.
	Usage *Usage `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	// duration_ms is the wall-clock time spent executing in the runtime.
	DurationMs int32 `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// invocation_id echoes InvocationRequest.invocation_id for correlation.
	InvocationId  string `protobuf:"bytes,4,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationResponse) Reset() {
	*x = InvocationResponse{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationResponse) ProtoMessage() {}

func (x *InvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationResponse.ProtoReflect.Descriptor instead.
func (*InvocationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *InvocationResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *InvocationResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *InvocationResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *InvocationResponse) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

// HealthRequest is an empty message for health checks.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{15}
}

// HealthResponse contains the health status of the runtime.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy indicates whether the runtime is ready to handle requests.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// status provides additional status information.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// contract_version is the omnia.runtime.v1 contract version this runtime
	// was built against, as a semver string (see the Contract-Version marker at
	// the top of this file). A runtime that reports an empty value predates
	// contract versioning and must be treated as unversioned.
	ContractVersion string `protobuf:"bytes,3,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	// capabilities lists the contract features this runtime implements (e.g.
	// "invoke", "duplex_audio", "client_tools"). An OPEN set — consumers must
	// display/ignore names they don't recognize. Empty => a pre-negotiation
	// (legacy) runtime.
	Capabilities  []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *HealthResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// HasConversationRequest asks whether one session's context is resumable.
type HasConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id is the conversation id to probe.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasConversationRequest) Reset() {
	*x = HasConversationRequest{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasConversationRequest) ProtoMessage() {}

func (x *HasConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasConversationRequest.ProtoReflect.Descriptor instead.
func (*HasConversationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *HasConversationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// HasConversationResponse reports one session's resume disposition.
type HasConversationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state is the disposition of the session's working context.
	State ResumeState `protobuf:"varint,1,opt,name=state,proto3,enum=omnia.runtime.v1.ResumeState" json:"state,omitempty"`
	// detail carries store-level error text when state is
	// RESUME_STATE_UNAVAILABLE. Diagnostic only; never surfaced to end clients.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasConversationResponse) Reset() {
	*x = HasConversationResponse{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasConversationResponse) ProtoMessage() {}

func (x *HasConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasConversationResponse.ProtoReflect.Descriptor instead.
func (*HasConversationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *HasConversationResponse) GetState() ResumeState {
	if x != nil {
		return x.State
	}
	return ResumeState_RESUME_STATE_UNSPECIFIED
}

func (x *HasConversationResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// DuplexStart opens a bidirectional audio session on a Converse stream.
type DuplexStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// codec is the audio encoding, e.g. "pcm".
	Codec string `protobuf:"bytes,1,opt,name=codec,proto3" json:"codec,omitempty"`
	// sample_rate in Hz, e.g. 16000.
	SampleRate int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// channels, e.g. 1 for mono.
	Channels int32 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	// system_instruction is the optional system prompt for the session.
	SystemInstruction string `protobuf:"bytes,4,opt,name=system_instruction,json=systemInstruction,proto3" json:"system_instruction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DuplexStart) Reset() {
	*x = DuplexStart{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplexStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplexStart) ProtoMessage() {}

func (x *DuplexStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplexStart.ProtoReflect.Descriptor instead.
func (*DuplexStart) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *DuplexStart) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *DuplexStart) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *DuplexStart) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *DuplexStart) GetSystemInstruction() string {
	if x != nil {
		return x.SystemInstruction
	}
	return ""
}

// AudioInputChunk is one inbound audio frame during a duplex session.
type AudioInputChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is raw audio bytes (never base64 on the gRPC path).
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// sequence is the 0-indexed frame number.
	Sequence uint32 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// is_last marks the final frame (client hangup / stream end).
	IsLast        bool `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioInputChunk) Reset() {
	*x = AudioInputChunk{}
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioInputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInputChunk) ProtoMessage() {}

func (x *AudioInputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInputChunk.ProtoReflect.Descriptor instead.
func (*AudioInputChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *AudioInputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioInputChunk) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AudioInputChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

var File_api_proto_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_api_proto_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/runtime/v1/runtime.proto\x12\x10omnia.runtime.v1\"\x84\x04\n" +
	"\rClientMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.omnia.runtime.v1.ClientMessage.MetadataEntryR\bmetadata\x123\n" +
	"\x05parts\x18\x04 \x03(\v2\x1d.omnia.runtime.v1.ContentPartR\x05parts\x12P\n" +
	"\x12client_tool_result\x18\x05 \x01(\v2\".omnia.runtime.v1.ClientToolResultR\x10clientToolResult\x12%\n" +
	"\x0econsent_grants\x18\x06 \x03(\tR\rconsentGrants\x12@\n" +
	"\fduplex_start\x18\a \x01(\v2\x1d.omnia.runtime.v1.DuplexStartR\vduplexStart\x12B\n" +
	"\vaudio_input\x18\b \x01(\v2!.omnia.runtime.v1.AudioInputChunkR\n" +
	"audioInput\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x10ClientToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x1f\n" +
	"\vis_rejected\x18\x03 \x01(\bR\n" +
	"isRejected\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\"\xec\x02\n" +
	"\rServerMessage\x12/\n" +
	"\x05chunk\x18\x01 \x01(\v2\x17.omnia.runtime.v1.ChunkH\x00R\x05chunk\x129\n" +
	"\ttool_call\x18\x02 \x01(\v2\x1a.omnia.runtime.v1.ToolCallH\x00R\btoolCall\x12,\n" +
	"\x04done\x18\x04 \x01(\v2\x16.omnia.runtime.v1.DoneH\x00R\x04done\x12/\n" +
	"\x05error\x18\x05 \x01(\v2\x17.omnia.runtime.v1.ErrorH\x00R\x05error\x12?\n" +
	"\vmedia_chunk\x18\x06 \x01(\v2\x1c.omnia.runtime.v1.MediaChunkH\x00R\n" +
	"mediaChunk\x12D\n" +
	"\finterruption\x18\a \x01(\v2\x1e.omnia.runtime.v1.InterruptionH\x00R\finterruptionB\t\n" +
	"\amessage\"!\n" +
	"\x05Chunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xdd\x01\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\x12=\n" +
	"\texecution\x18\x04 \x01(\x0e2\x1f.omnia.runtime.v1.ToolExecutionR\texecution\x12'\n" +
	"\x0fconsent_message\x18\x05 \x01(\tR\x0econsentMessage\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\"X\n" +
	"\n" +
	"ToolResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"\x8f\x01\n" +
	"\x04Done\x12#\n" +
	"\rfinal_content\x18\x01 \x01(\tR\ffinalContent\x12-\n" +
	"\x05usage\x18\x02 \x01(\v2\x17.omnia.runtime.v1.UsageR\x05usage\x123\n" +
	"\x05parts\x18\x03 \x03(\v2\x1d.omnia.runtime.v1.ContentPartR\x05parts\"k\n" +
	"\vContentPart\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x124\n" +
	"\x05media\x18\x03 \x01(\v2\x1e.omnia.runtime.v1.MediaContentR\x05media\"r\n" +
	"\fMediaContent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vstorage_ref\x18\x04 \x01(\tR\n" +
	"storageRef\"j\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12\x19\n" +
	"\bcost_usd\x18\x03 \x01(\x02R\acostUsd\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fInterruption\"\x8d\x01\n" +
	"\n" +
	"MediaChunk\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"\xe3\x01\n" +
	"\x11InvocationRequest\x12\x1d\n" +
	"\n" +
	"input_json\x18\x01 \x01(\tR\tinputJson\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12M\n" +
	"\bmetadata\x18\x03 \x03(\v21.omnia.runtime.v1.InvocationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x12InvocationResponse\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\x12-\n" +
	"\x05usage\x18\x02 \x01(\v2\x17.omnia.runtime.v1.UsageR\x05usage\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\x12#\n" +
	"\rinvocation_id\x18\x04 \x01(\tR\finvocationId\"\x0f\n" +
	"\rHealthRequest\"\x91\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10contract_version\x18\x03 \x01(\tR\x0fcontractVersion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"7\n" +
	"\x16HasConversationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"f\n" +
	"\x17HasConversationResponse\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.omnia.runtime.v1.ResumeStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x8f\x01\n" +
	"\vDuplexStart\x12\x14\n" +
	"\x05codec\x18\x01 \x01(\tR\x05codec\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\x12-\n" +
	"\x12system_instruction\x18\x04 \x01(\tR\x11systemInstruction\"Z\n" +
	"\x0fAudioInputChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast*E\n" +
	"\rToolExecution\x12\x19\n" +
	"\x15TOOL_EXECUTION_SERVER\x10\x00\x12\x19\n" +
	"\x15TOOL_EXECUTION_CLIENT\x10\x01*\x81\x01\n" +
	"\vResumeState\x12\x1c\n" +
	"\x18RESUME_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RESUME_STATE_RESUMABLE\x10\x01\x12\x1a\n" +
	"\x16RESUME_STATE_NOT_FOUND\x10\x02\x12\x1c\n" +
	"\x18RESUME_STATE_UNAVAILABLE\x10\x032\xec\x02\n" +
	"\x0eRuntimeService\x12P\n" +
	"\bConverse\x12\x1f.omnia.runtime.v1.ClientMessage\x1a\x1f.omnia.runtime.v1.ServerMessage(\x010\x01\x12S\n" +
	"\x06Invoke\x12#.omnia.runtime.v1.InvocationRequest\x1a$.omnia.runtime.v1.InvocationResponse\x12K\n" +
	"\x06Health\x12\x1f.omnia.runtime.v1.HealthRequest\x1a .omnia.runtime.v1.HealthResponse\x12f\n" +
	"\x0fHasConversation\x12(.omnia.runtime.v1.HasConversationRequest\x1a).omnia.runtime.v1.HasConversationResponseB7Z5github.com/altairalabs/omnia/pkg/runtime/v1;runtimev1b\x06proto3"

var (
	file_api_proto_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_api_proto_runtime_v1_runtime_proto_rawDescData []byte
)

func file_api_proto_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_api_proto_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_api_proto_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_runtime_v1_runtime_proto_rawDesc), len(file_api_proto_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_api_proto_runtime_v1_runtime_proto_rawDescData
}

var file_api_proto_runtime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_runtime_v1_runtime_proto_goTypes = []any{
	(ToolExecution)(0),              // 0: omnia.runtime.v1.ToolExecution
	(ResumeState)(0),                // 1: omnia.runtime.v1.ResumeState
	(*ClientMessage)(nil),           // 2: omnia.runtime.v1.ClientMessage
	(*ClientToolResult)(nil),        // 3: omnia.runtime.v1.ClientToolResult
	(*ServerMessage)(nil),           // 4: omnia.runtime.v1.ServerMessage
	(*Chunk)(nil),                   // 5: omnia.runtime.v1.Chunk
	(*ToolCall)(nil),                // 6: omnia.runtime.v1.ToolCall
	(*ToolResult)(nil),              // 7: omnia.runtime.v1.ToolResult
	(*Done)(nil),                    // 8: omnia.runtime.v1.Done
	(*ContentPart)(nil),             // 9: omnia.runtime.v1.ContentPart
	(*MediaContent)(nil),            // 10: omnia.runtime.v1.MediaContent
	(*Usage)(nil),                   // 11: omnia.runtime.v1.Usage
	(*Error)(nil),                   // 12: omnia.runtime.v1.Error
	(*Interruption)(nil),            // 13: omnia.runtime.v1.Interruption
	(*MediaChunk)(nil),              // 14: omnia.runtime.v1.MediaChunk
	(*InvocationRequest)(nil),       // 15: omnia.runtime.v1.InvocationRequest
	(*InvocationResponse)(nil),      // 16: omnia.runtime.v1.InvocationResponse
	(*HealthRequest)(nil),           // 17: omnia.runtime.v1.HealthRequest
	(*HealthResponse)(nil),          // 18: omnia.runtime.v1.HealthResponse
	(*HasConversationRequest)(nil),  // 19: omnia.runtime.v1.HasConversationRequest
	(*HasConversationResponse)(nil), // 20: omnia.runtime.v1.HasConversationResponse
	(*DuplexStart)(nil),             // 21: omnia.runtime.v1.DuplexStart
	(*AudioInputChunk)(nil),         // 22: omnia.runtime.v1.AudioInputChunk
	nil,                             // 23: omnia.runtime.v1.ClientMessage.MetadataEntry
	nil,                             // 24: omnia.runtime.v1.InvocationRequest.MetadataEntry
}
var file_api_proto_runtime_v1_runtime_proto_depIdxs = []int32{
	23, // 0: omnia.runtime.v1.ClientMessage.metadata:type_name -> omnia.runtime.v1.ClientMessage.MetadataEntry
	9,  // 1: omnia.runtime.v1.ClientMessage.parts:type_name -> omnia.runtime.v1.ContentPart
	3,  // 2: omnia.runtime.v1.ClientMessage.client_tool_result:type_name -> omnia.runtime.v1.ClientToolResult
	21, // 3: omnia.runtime.v1.ClientMessage.duplex_start:type_name -> omnia.runtime.v1.DuplexStart
	22, // 4: omnia.runtime.v1.ClientMessage.audio_input:type_name -> omnia.runtime.v1.AudioInputChunk
	5,  // 5: omnia.runtime.v1.ServerMessage.chunk:type_name -> omnia.runtime.v1.Chunk
	6,  // 6: omnia.runtime.v1.ServerMessage.tool_call:type_name -> omnia.runtime.v1.ToolCall
	8,  // 7: omnia.runtime.v1.ServerMessage.done:type_name -> omnia.runtime.v1.Done
	12, // 8: omnia.runtime.v1.ServerMessage.error:type_name -> omnia.runtime.v1.Error
	14, // 9: omnia.runtime.v1.ServerMessage.media_chunk:type_name -> omnia.runtime.v1.MediaChunk
	13, // 10: omnia.runtime.v1.ServerMessage.interruption:type_name -> omnia.runtime.v1.Interruption
	0,  // 11: omnia.runtime.v1.ToolCall.execution:type_name -> omnia.runtime.v1.ToolExecution
	11, // 12: omnia.runtime.v1.Done.usage:type_name -> omnia.runtime.v1.Usage
	9,  // 13: omnia.runtime.v1.Done.parts:type_name -> omnia.runtime.v1.ContentPart
	10, // 14: omnia.runtime.v1.ContentPart.media:type_name -> omnia.runtime.v1.MediaContent
	24, // 15: omnia.runtime.v1.InvocationRequest.metadata:type_name -> omnia.runtime.v1.InvocationRequest.MetadataEntry
	11, // 16: omnia.runtime.v1.InvocationResponse.usage:type_name -> omnia.runtime.v1.Usage
	1,  // 17: omnia.runtime.v1.HasConversationResponse.state:type_name -> omnia.runtime.v1.ResumeState
	2,  // 18: omnia.runtime.v1.RuntimeService.Converse:input_type -> omnia.runtime.v1.ClientMessage
	15, // 19: omnia.runtime.v1.RuntimeService.Invoke:input_type -> omnia.runtime.v1.InvocationRequest
	17, // 20: omnia.runtime.v1.RuntimeService.Health:input_type -> omnia.runtime.v1.HealthRequest
	19, // 21: omnia.runtime.v1.RuntimeService.HasConversation:input_type -> omnia.runtime.v1.HasConversationRequest
	4,  // 22: omnia.runtime.v1.RuntimeService.Converse:output_type -> omnia.runtime.v1.ServerMessage
	16, // 23: omnia.runtime.v1.RuntimeService.Invoke:output_type -> omnia.runtime.v1.InvocationResponse
	18, // 24: omnia.runtime.v1.RuntimeService.Health:output_type -> omnia.runtime.v1.HealthResponse
	20, // 25: omnia.runtime.v1.RuntimeService.HasConversation:output_type -> omnia.runtime.v1.HasConversationResponse
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_runtime_v1_runtime_proto_init() }
func file_api_proto_runtime_v1_runtime_proto_init() {
	if File_api_proto_runtime_v1_runtime_proto != nil {
		return
	}
	file_api_proto_runtime_v1_runtime_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerMessage_Chunk)(nil),
		(*ServerMessage_ToolCall)(nil),
		(*ServerMessage_Done)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_MediaChunk)(nil),
		(*ServerMessage_Interruption)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_runtime_v1_runtime_proto_rawDesc), len(file_api_proto_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_api_proto_runtime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_api_proto_runtime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_api_proto_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_api_proto_runtime_v1_runtime_proto = out.File
	file_api_proto_runtime_v1_runtime_proto_goTypes = nil
	file_api_proto_runtime_v1_runtime_proto_depIdxs = nil
}
