// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.0
// source: tools/v1/tools.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/** ToolRequest contains the request to execute a tool. */
export interface ToolRequest {
  /** tool_name identifies which tool to execute. */
  toolName: string;
  /**
   * arguments_json contains the tool arguments as a JSON string.
   * The schema depends on the specific tool being invoked.
   */
  argumentsJson: string;
  /** metadata contains optional key-value pairs for additional context. */
  metadata: { [key: string]: string };
}

export interface ToolRequest_MetadataEntry {
  key: string;
  value: string;
}

/** ToolResponse contains the result of a tool execution. */
export interface ToolResponse {
  /** result_json contains the tool result as a JSON string. */
  resultJson: string;
  /** is_error indicates whether the tool execution failed. */
  isError: boolean;
  /** error_message contains the error description if is_error is true. */
  errorMessage: string;
}

/** ListToolsRequest is the request to list available tools. */
export interface ListToolsRequest {
}

/** ListToolsResponse contains the list of available tools. */
export interface ListToolsResponse {
  /** tools is the list of available tools. */
  tools: ToolInfo[];
}

/** ToolInfo describes a single tool. */
export interface ToolInfo {
  /** name is the unique identifier for this tool. */
  name: string;
  /** description describes what the tool does. */
  description: string;
  /** input_schema is a JSON schema describing the tool's input parameters. */
  inputSchema: string;
}

function createBaseToolRequest(): ToolRequest {
  return { toolName: "", argumentsJson: "", metadata: {} };
}

export const ToolRequest: MessageFns<ToolRequest> = {
  encode(message: ToolRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.toolName !== "") {
      writer.uint32(10).string(message.toolName);
    }
    if (message.argumentsJson !== "") {
      writer.uint32(18).string(message.argumentsJson);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      ToolRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.toolName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.argumentsJson = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = ToolRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.metadata[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolRequest {
    return {
      toolName: isSet(object.tool_name) ? globalThis.String(object.tool_name) : "",
      argumentsJson: isSet(object.arguments_json) ? globalThis.String(object.arguments_json) : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ToolRequest): unknown {
    const obj: any = {};
    if (message.toolName !== "") {
      obj.tool_name = message.toolName;
    }
    if (message.argumentsJson !== "") {
      obj.arguments_json = message.argumentsJson;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolRequest>, I>>(base?: I): ToolRequest {
    return ToolRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolRequest>, I>>(object: I): ToolRequest {
    const message = createBaseToolRequest();
    message.toolName = object.toolName ?? "";
    message.argumentsJson = object.argumentsJson ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseToolRequest_MetadataEntry(): ToolRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const ToolRequest_MetadataEntry: MessageFns<ToolRequest_MetadataEntry> = {
  encode(message: ToolRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ToolRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolRequest_MetadataEntry>, I>>(base?: I): ToolRequest_MetadataEntry {
    return ToolRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolRequest_MetadataEntry>, I>>(object: I): ToolRequest_MetadataEntry {
    const message = createBaseToolRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseToolResponse(): ToolResponse {
  return { resultJson: "", isError: false, errorMessage: "" };
}

export const ToolResponse: MessageFns<ToolResponse> = {
  encode(message: ToolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resultJson !== "") {
      writer.uint32(10).string(message.resultJson);
    }
    if (message.isError !== false) {
      writer.uint32(16).bool(message.isError);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resultJson = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isError = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolResponse {
    return {
      resultJson: isSet(object.result_json) ? globalThis.String(object.result_json) : "",
      isError: isSet(object.is_error) ? globalThis.Boolean(object.is_error) : false,
      errorMessage: isSet(object.error_message) ? globalThis.String(object.error_message) : "",
    };
  },

  toJSON(message: ToolResponse): unknown {
    const obj: any = {};
    if (message.resultJson !== "") {
      obj.result_json = message.resultJson;
    }
    if (message.isError !== false) {
      obj.is_error = message.isError;
    }
    if (message.errorMessage !== "") {
      obj.error_message = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolResponse>, I>>(base?: I): ToolResponse {
    return ToolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolResponse>, I>>(object: I): ToolResponse {
    const message = createBaseToolResponse();
    message.resultJson = object.resultJson ?? "";
    message.isError = object.isError ?? false;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseListToolsRequest(): ListToolsRequest {
  return {};
}

export const ListToolsRequest: MessageFns<ListToolsRequest> = {
  encode(_: ListToolsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListToolsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListToolsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListToolsRequest {
    return {};
  },

  toJSON(_: ListToolsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListToolsRequest>, I>>(base?: I): ListToolsRequest {
    return ListToolsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListToolsRequest>, I>>(_: I): ListToolsRequest {
    const message = createBaseListToolsRequest();
    return message;
  },
};

function createBaseListToolsResponse(): ListToolsResponse {
  return { tools: [] };
}

export const ListToolsResponse: MessageFns<ListToolsResponse> = {
  encode(message: ListToolsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tools) {
      ToolInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListToolsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListToolsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tools.push(ToolInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListToolsResponse {
    return { tools: globalThis.Array.isArray(object?.tools) ? object.tools.map((e: any) => ToolInfo.fromJSON(e)) : [] };
  },

  toJSON(message: ListToolsResponse): unknown {
    const obj: any = {};
    if (message.tools?.length) {
      obj.tools = message.tools.map((e) => ToolInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListToolsResponse>, I>>(base?: I): ListToolsResponse {
    return ListToolsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListToolsResponse>, I>>(object: I): ListToolsResponse {
    const message = createBaseListToolsResponse();
    message.tools = object.tools?.map((e) => ToolInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseToolInfo(): ToolInfo {
  return { name: "", description: "", inputSchema: "" };
}

export const ToolInfo: MessageFns<ToolInfo> = {
  encode(message: ToolInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.inputSchema !== "") {
      writer.uint32(26).string(message.inputSchema);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.inputSchema = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolInfo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      inputSchema: isSet(object.input_schema) ? globalThis.String(object.input_schema) : "",
    };
  },

  toJSON(message: ToolInfo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.inputSchema !== "") {
      obj.input_schema = message.inputSchema;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolInfo>, I>>(base?: I): ToolInfo {
    return ToolInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolInfo>, I>>(object: I): ToolInfo {
    const message = createBaseToolInfo();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.inputSchema = object.inputSchema ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
