#!/usr/bin/env bash
#
# Register (or rotate credentials for) an Entra ID app for local Omnia dashboard
# OAuth development, and populate the K8s secret the Helm chart expects.
#
# Usage:
#   scripts/setup-entra-dev.sh                       # print env vars + values snippet
#   scripts/setup-entra-dev.sh --create-secret       # also create/update K8s secret
#   APP_NAME="Omnia Dev (alice)" scripts/setup-entra-dev.sh --create-secret
#
# Env overrides:
#   APP_NAME       display name for the app registration (default: "Omnia Dashboard Dev")
#   REDIRECT_URI   redirect URI (default: http://localhost:3000/api/auth/callback)
#   SECRET_YEARS   client secret lifetime in years (default: 1, Azure max: 2)
#   NAMESPACE      K8s namespace for the Secret (default: omnia-system)
#   SECRET_NAME    K8s Secret name (default: dashboard-oauth)
#
# Requires: az (logged in via `az login`), jq, openssl;
#           kubectl only if --create-secret is passed.

set -euo pipefail

APP_NAME="${APP_NAME:-Omnia Dashboard Dev}"
REDIRECT_URI="${REDIRECT_URI:-http://localhost:3000/api/auth/callback}"
SECRET_YEARS="${SECRET_YEARS:-1}"
NAMESPACE="${NAMESPACE:-omnia-system}"
SECRET_NAME="${SECRET_NAME:-dashboard-oauth}"
CREATE_SECRET=false

for arg in "$@"; do
  case "$arg" in
    --create-secret) CREATE_SECRET=true ;;
    -h|--help)
      sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

for cmd in az jq openssl; do
  command -v "$cmd" >/dev/null || { echo "required command not found: $cmd" >&2; exit 1; }
done
if $CREATE_SECRET; then
  command -v kubectl >/dev/null || { echo "kubectl required for --create-secret" >&2; exit 1; }
fi

az account show >/dev/null 2>&1 || { echo "run 'az login' first" >&2; exit 1; }

TENANT_ID=$(az account show --query tenantId -o tsv)

# Idempotent: reuse an existing app with the same display name if one exists.
APP_ID=$(az ad app list --display-name "$APP_NAME" --query '[0].appId' -o tsv)

if [[ -z "$APP_ID" ]]; then
  echo ">> creating app registration: $APP_NAME" >&2
  APP_ID=$(az ad app create \
    --display-name "$APP_NAME" \
    --sign-in-audience AzureADMyOrg \
    --web-redirect-uris "$REDIRECT_URI" \
    --query appId -o tsv)
else
  echo ">> reusing existing app: $APP_NAME (appId=$APP_ID)" >&2
  # Make sure the redirect URI is registered (idempotent append).
  UPDATED_URIS=$(az ad app show --id "$APP_ID" --query 'web.redirectUris' -o json \
    | jq --arg uri "$REDIRECT_URI" 'if index($uri) then . else . + [$uri] end')
  if [[ "$UPDATED_URIS" != "$(az ad app show --id "$APP_ID" --query 'web.redirectUris' -o json)" ]]; then
    # --web-redirect-uris takes a space-separated list; splat from jq.
    # shellcheck disable=SC2046
    az ad app update --id "$APP_ID" --web-redirect-uris $(jq -r '.[]' <<<"$UPDATED_URIS")
  fi
fi

echo ">> resetting client secret (append mode, ${SECRET_YEARS}y validity)" >&2
CLIENT_SECRET=$(az ad app credential reset \
  --id "$APP_ID" \
  --years "$SECRET_YEARS" \
  --append \
  --display-name "omnia-dev-$(date +%Y%m%d)" \
  --query password -o tsv)

SESSION_SECRET=$(openssl rand -base64 32)

if $CREATE_SECRET; then
  echo ">> creating/updating Secret $NAMESPACE/$SECRET_NAME" >&2
  kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  kubectl create secret generic "$SECRET_NAME" \
    --namespace "$NAMESPACE" \
    --from-literal=OMNIA_OAUTH_CLIENT_ID="$APP_ID" \
    --from-literal=OMNIA_OAUTH_CLIENT_SECRET="$CLIENT_SECRET" \
    --from-literal=OMNIA_SESSION_SECRET="$SESSION_SECRET" \
    --dry-run=client -o yaml \
    | kubectl apply -f - >/dev/null
fi

# Write a gitignored values file so `ENABLE_ENTRA=true tilt up` picks up the
# tenant ID and secret refs without requiring shell exports.
VALUES_FILE="$(cd "$(dirname "$0")/.." && pwd)/charts/omnia/values-dev-entra.yaml"
cat > "$VALUES_FILE" <<EOF
# Generated by scripts/setup-entra-dev.sh — do not commit.
# Regenerate by rerunning the script.
dashboard:
  auth:
    mode: oauth
    existingSessionSecret: $SECRET_NAME
  oauth:
    provider: azure
    azureTenantId: "$TENANT_ID"
    existingSecret: $SECRET_NAME
EOF
echo ">> wrote $VALUES_FILE" >&2

cat <<EOF

# ─── Entra app ready ────────────────────────────────────────────────────────
# Tenant:     $TENANT_ID
# AppId:      $APP_ID
# Redirect:   $REDIRECT_URI
# K8s secret: $(if $CREATE_SECRET; then echo "created → $NAMESPACE/$SECRET_NAME"; else echo "NOT created (pass --create-secret to create)"; fi)
#
# Next steps for Tilt:
#
#   1. Ensure the Secret exists (rerun with --create-secret if you skipped it).
#
#   2. Start Tilt with Entra enabled:
#        ENABLE_ENTRA=true tilt up
#
#   3. (Optional) To enable group-based roles, add a 'groups' optional claim in
#      the Azure Portal → App registrations → Token configuration, then set:
#        dashboard.auth.roleMapping.admin={group-object-id-1}
#
# ────────────────────────────────────────────────────────────────────────────
EOF
