// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.0
// source: runtime/v1/runtime.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/** ToolExecution indicates where a tool is executed. */
export enum ToolExecution {
  /** TOOL_EXECUTION_SERVER - TOOL_EXECUTION_SERVER means the tool runs server-side in the runtime. */
  TOOL_EXECUTION_SERVER = 0,
  /** TOOL_EXECUTION_CLIENT - TOOL_EXECUTION_CLIENT means the tool must be fulfilled by the client. */
  TOOL_EXECUTION_CLIENT = 1,
  UNRECOGNIZED = -1,
}

export function toolExecutionFromJSON(object: any): ToolExecution {
  switch (object) {
    case 0:
    case "TOOL_EXECUTION_SERVER":
      return ToolExecution.TOOL_EXECUTION_SERVER;
    case 1:
    case "TOOL_EXECUTION_CLIENT":
      return ToolExecution.TOOL_EXECUTION_CLIENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ToolExecution.UNRECOGNIZED;
  }
}

export function toolExecutionToJSON(object: ToolExecution): string {
  switch (object) {
    case ToolExecution.TOOL_EXECUTION_SERVER:
      return "TOOL_EXECUTION_SERVER";
    case ToolExecution.TOOL_EXECUTION_CLIENT:
      return "TOOL_EXECUTION_CLIENT";
    case ToolExecution.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ResumeState is the disposition of a session's working context.
 *
 * The three states exist because the facade must act differently on each: a
 * missing conversation is a client-visible expiry, whereas an unreachable
 * store is a server fault. Collapsing them would recreate the bug this RPC
 * exists to fix — telling a client its session expired when in fact the
 * context is intact and the store was merely briefly unreachable.
 */
export enum ResumeState {
  /** RESUME_STATE_UNSPECIFIED - Unset. Treated as RESUME_STATE_UNAVAILABLE by callers. */
  RESUME_STATE_UNSPECIFIED = 0,
  /** RESUME_STATE_RESUMABLE - Context is present; sdk.Resume will succeed. */
  RESUME_STATE_RESUMABLE = 1,
  /**
   * RESUME_STATE_NOT_FOUND - Store answered definitively that no context exists for this id — it
   * expired, or was never persisted. The session cannot be continued.
   */
  RESUME_STATE_NOT_FOUND = 2,
  /**
   * RESUME_STATE_UNAVAILABLE - The store could not be consulted (unreachable, timed out, or no store is
   * configured). Resumability is unknown; this is NOT an expiry.
   */
  RESUME_STATE_UNAVAILABLE = 3,
  UNRECOGNIZED = -1,
}

export function resumeStateFromJSON(object: any): ResumeState {
  switch (object) {
    case 0:
    case "RESUME_STATE_UNSPECIFIED":
      return ResumeState.RESUME_STATE_UNSPECIFIED;
    case 1:
    case "RESUME_STATE_RESUMABLE":
      return ResumeState.RESUME_STATE_RESUMABLE;
    case 2:
    case "RESUME_STATE_NOT_FOUND":
      return ResumeState.RESUME_STATE_NOT_FOUND;
    case 3:
    case "RESUME_STATE_UNAVAILABLE":
      return ResumeState.RESUME_STATE_UNAVAILABLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ResumeState.UNRECOGNIZED;
  }
}

export function resumeStateToJSON(object: ResumeState): string {
  switch (object) {
    case ResumeState.RESUME_STATE_UNSPECIFIED:
      return "RESUME_STATE_UNSPECIFIED";
    case ResumeState.RESUME_STATE_RESUMABLE:
      return "RESUME_STATE_RESUMABLE";
    case ResumeState.RESUME_STATE_NOT_FOUND:
      return "RESUME_STATE_NOT_FOUND";
    case ResumeState.RESUME_STATE_UNAVAILABLE:
      return "RESUME_STATE_UNAVAILABLE";
    case ResumeState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ClientMessage represents a message from the client to the runtime. */
export interface ClientMessage {
  /** session_id identifies the conversation session for state management. */
  sessionId: string;
  /**
   * content is the user's message text (legacy, for backward compatibility).
   * For multimodal messages, use the parts field instead.
   */
  content: string;
  /** metadata contains optional key-value pairs for additional context. */
  metadata: { [key: string]: string };
  /**
   * parts contains multimodal content parts (text, images, audio, video, files).
   * If non-empty, this takes precedence over the content field.
   */
  parts: ContentPart[];
  /**
   * client_tool_result carries the result of a client-side tool execution.
   * Set when responding to a ToolCall with execution=CLIENT.
   */
  clientToolResult?:
    | ClientToolResult
    | undefined;
  /**
   * consent_grants carries per-message consent category grants from the client.
   * When present, these override stored consent for this request.
   */
  consentGrants: string[];
  /**
   * duplex_start, when set on the first message of a Converse stream, switches
   * the stream into bidirectional audio mode (OSS duplex transport).
   */
  duplexStart?:
    | DuplexStart
    | undefined;
  /** audio_input carries one inbound audio frame during a duplex session. */
  audioInput?: AudioInputChunk | undefined;
}

export interface ClientMessage_MetadataEntry {
  key: string;
  value: string;
}

/** ClientToolResult carries the client's response to a client-side tool call. */
export interface ClientToolResult {
  /** call_id matches the ToolCall.id that this result is for. */
  callId: string;
  /** result_json contains the tool result as a JSON string. */
  resultJson: string;
  /** is_rejected indicates the client rejected the tool call. */
  isRejected: boolean;
  /** rejection_reason explains why the client rejected the tool call. */
  rejectionReason: string;
}

/**
 * ServerMessage represents a message from the runtime to the client.
 * Uses oneof to ensure only one message type is sent at a time.
 */
export interface ServerMessage {
  message?:
    | //
    /** chunk contains a partial text response for streaming. */
    { $case: "chunk"; chunk: Chunk }
    | //
    /**
     * tool_call notifies the facade of a client-side tool invocation.
     * The facade forwards this to the WebSocket client, which must respond
     * with a ClientToolResult before the conversation can continue.
     * Server-side tool calls are handled internally by the runtime and
     * are not sent on this stream.
     */
    { $case: "toolCall"; toolCall: ToolCall }
    | //
    /** done signals the completion of a response. */
    { $case: "done"; done: Done }
    | //
    /** error indicates an error occurred during processing. */
    { $case: "error"; error: Error }
    | //
    /**
     * media_chunk contains a streaming media chunk (image, audio, video).
     * Sent during streaming when the LLM produces media content, allowing
     * the client to begin processing before the entire media is available.
     */
    { $case: "mediaChunk"; mediaChunk: MediaChunk }
    | //
    /** interruption signals a barge-in; the client clears buffered audio. */
    { $case: "interruption"; interruption: Interruption }
    | //
    /**
     * runtime_hello is the runtime's first ServerMessage on a Converse stream:
     * the session's authoritative capability set plus, for a duplex session, a
     * bounded media counter-offer (codec/sample_rate/channels) the facade
     * relays to the client. A runtime that never sends a hello is legacy — the
     * facade proceeds with today's unilateral DuplexStart behaviour.
     */
    { $case: "runtimeHello"; runtimeHello: RuntimeHello }
    | undefined;
}

/** Chunk contains a partial text response for streaming output. */
export interface Chunk {
  /** content is the text chunk to append to the response. */
  content: string;
}

/**
 * ToolCall represents a tool invocation.
 * For server-side tools this is informational (UI display only).
 * For client-side tools the client must send back a ClientToolResult.
 */
export interface ToolCall {
  /** id is a unique identifier for this tool call. */
  id: string;
  /** name is the name of the tool being called. */
  name: string;
  /** arguments_json contains the tool arguments as a JSON string. */
  argumentsJson: string;
  /** execution indicates whether this tool runs server-side or client-side. */
  execution: ToolExecution;
  /** consent_message is a human-readable consent prompt for client-side tools. */
  consentMessage: string;
  /** categories are semantic consent categories (e.g., "location", "filesystem"). */
  categories: string[];
}

/** ToolResult contains the result of a tool execution (informational for UI display). */
export interface ToolResult {
  /** id matches the corresponding ToolCall id. */
  id: string;
  /** result_json contains the tool result as a JSON string. */
  resultJson: string;
  /** is_error indicates whether the tool execution failed. */
  isError: boolean;
}

/** Done signals the completion of a conversation turn. */
export interface Done {
  /**
   * final_content contains the complete response text (optional).
   * For text-only responses, this contains the full response.
   * For multimodal responses, use the parts field instead.
   */
  finalContent: string;
  /** usage contains token usage statistics for this turn. */
  usage?:
    | Usage
    | undefined;
  /**
   * parts contains multimodal content parts (text, images, audio, video).
   * If non-empty, this takes precedence over final_content for rich responses.
   */
  parts: ContentPart[];
}

/** ContentPart represents a single piece of content in a multimodal message. */
export interface ContentPart {
  /** type indicates the content type: "text", "image", "audio", "video" */
  type: string;
  /** text contains text content (only set when type="text") */
  text: string;
  /** media contains media content (only set when type="image", "audio", or "video") */
  media?: MediaContent | undefined;
}

/** MediaContent represents media data (image, audio, video) in a message. */
export interface MediaContent {
  /** data contains base64-encoded media data (for resolved file:// and mock:// URLs) */
  data: string;
  /** url contains the media URL (for http:// and https:// URLs that are passed through) */
  url: string;
  /** mime_type indicates the media format (e.g., "image/png", "audio/mp3") */
  mimeType: string;
  /**
   * storage_ref is an opaque backend storage reference (e.g. "omnia://sessions/{id}/media/{mediaID}").
   * When set, the runtime resolves it to media bytes at provider-call time via the injected media store.
   */
  storageRef: string;
}

/** Usage contains token usage and cost information. */
export interface Usage {
  /** input_tokens is the number of tokens in the input/prompt. */
  inputTokens: number;
  /** output_tokens is the number of tokens in the output/response. */
  outputTokens: number;
  /** cost_usd is the estimated cost in USD for this request. */
  costUsd: number;
}

/** Error represents an error that occurred during processing. */
export interface Error {
  /** code is a machine-readable error code. */
  code: string;
  /** message is a human-readable error description. */
  message: string;
}

/**
 * Interruption signals that the in-flight response was interrupted (e.g. the
 * user started speaking over the agent during a duplex session). The client
 * must clear any buffered audio playback immediately.
 */
export interface Interruption {
}

/**
 * MediaChunk contains a streaming media chunk for progressive media delivery.
 * All chunks sharing the same media_id belong to the same media stream.
 */
export interface MediaChunk {
  /** media_id is the unique identifier for this media stream. */
  mediaId: string;
  /** sequence is the 0-indexed sequence number for ordering chunks. */
  sequence: number;
  /** is_last indicates this is the final chunk for this media stream. */
  isLast: boolean;
  /** mime_type indicates the media format (e.g., "image/png", "audio/mp3"). */
  mimeType: string;
  /** data contains raw media bytes (avoids base64 overhead in gRPC path). */
  data: Uint8Array;
}

/** InvocationRequest carries a Function call from the facade. */
export interface InvocationRequest {
  /**
   * input_json is the raw JSON payload submitted by the caller. The facade
   * has already validated this against AgentRuntime.spec.inputSchema; the
   * runtime treats it as an opaque user message body.
   */
  inputJson: string;
  /**
   * invocation_id is a UUID for this Function call, used for log and
   * trace correlation. Assigned by the facade.
   */
  invocationId: string;
  /**
   * metadata carries optional key-value context (caller identity, auth
   * subject, custom headers). Not interpreted by the runtime.
   */
  metadata: { [key: string]: string };
}

export interface InvocationRequest_MetadataEntry {
  key: string;
  value: string;
}

/**
 * InvocationResponse carries the runtime's reply to the facade. On
 * success the facade then validates output_json against
 * AgentRuntime.spec.outputSchema before returning to the HTTP caller.
 */
export interface InvocationResponse {
  /**
   * output_json is the raw assistant text. The facade validates it
   * against the output schema; if invalid, the facade returns HTTP 502
   * with this raw payload in the response body (per Q2 lock on #1103).
   */
  outputJson: string;
  /** usage contains token + cost statistics for the call. */
  usage?:
    | Usage
    | undefined;
  /** duration_ms is the wall-clock time spent executing in the runtime. */
  durationMs: number;
  /** invocation_id echoes InvocationRequest.invocation_id for correlation. */
  invocationId: string;
}

/** HealthRequest is an empty message for health checks. */
export interface HealthRequest {
}

/** HealthResponse contains the health status of the runtime. */
export interface HealthResponse {
  /** healthy indicates whether the runtime is ready to handle requests. */
  healthy: boolean;
  /** status provides additional status information. */
  status: string;
  /**
   * contract_version is the omnia.runtime.v1 contract version this runtime
   * was built against, as a semver string (see the Contract-Version marker at
   * the top of this file). A runtime that reports an empty value predates
   * contract versioning and must be treated as unversioned.
   */
  contractVersion: string;
  /**
   * capabilities lists the contract features this runtime implements (e.g.
   * "invoke", "duplex_audio", "client_tools"). An OPEN set — consumers must
   * display/ignore names they don't recognize. Empty => a pre-negotiation
   * (legacy) runtime.
   */
  capabilities: string[];
}

/** HasConversationRequest asks whether one session's context is resumable. */
export interface HasConversationRequest {
  /** session_id is the conversation id to probe. */
  sessionId: string;
}

/** HasConversationResponse reports one session's resume disposition. */
export interface HasConversationResponse {
  /** state is the disposition of the session's working context. */
  state: ResumeState;
  /**
   * detail carries store-level error text when state is
   * RESUME_STATE_UNAVAILABLE. Diagnostic only; never surfaced to end clients.
   */
  detail: string;
}

/** DuplexStart opens a bidirectional audio session on a Converse stream. */
export interface DuplexStart {
  /** codec is the audio encoding, e.g. "pcm". */
  codec: string;
  /** sample_rate in Hz, e.g. 16000. */
  sampleRate: number;
  /** channels, e.g. 1 for mono. */
  channels: number;
  /** system_instruction is the optional system prompt for the session. */
  systemInstruction: string;
}

/**
 * RuntimeHello is the runtime's first ServerMessage on a Converse stream. It
 * carries the session's authoritative capability set and, for a duplex session,
 * the media parameters the runtime requires — a bounded counter-offer to the
 * facade's DuplexStart proposal. Absence of a hello marks a legacy runtime.
 */
export interface RuntimeHello {
  /**
   * capabilities is the per-session, authoritative capability set (open set;
   * consumers display or ignore unknown values).
   */
  capabilities: string[];
  /** media is the bounded media counter-offer. Set only for a duplex session. */
  media?: MediaNegotiation | undefined;
}

/**
 * MediaNegotiation is the bounded counter-offer parameter set. A zero value for
 * a field means "no requirement / accept the client's proposal" for that field.
 */
export interface MediaNegotiation {
  /** codec is the required audio encoding, e.g. "pcm". */
  codec: string;
  /** sample_rate is the required sample rate in Hz, e.g. 24000. */
  sampleRate: number;
  /** channels is the required channel count, e.g. 1 for mono. */
  channels: number;
  /** frame_rate is the required video frame rate (carried, not yet enforced). */
  frameRate: number;
  /** resolution is the required video resolution (carried, not yet enforced). */
  resolution: number;
}

/** AudioInputChunk is one inbound audio frame during a duplex session. */
export interface AudioInputChunk {
  /** data is raw audio bytes (never base64 on the gRPC path). */
  data: Uint8Array;
  /** sequence is the 0-indexed frame number. */
  sequence: number;
  /** is_last marks the final frame (client hangup / stream end). */
  isLast: boolean;
}

function createBaseClientMessage(): ClientMessage {
  return {
    sessionId: "",
    content: "",
    metadata: {},
    parts: [],
    clientToolResult: undefined,
    consentGrants: [],
    duplexStart: undefined,
    audioInput: undefined,
  };
}

export const ClientMessage: MessageFns<ClientMessage> = {
  encode(message: ClientMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      ClientMessage_MetadataEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    for (const v of message.parts) {
      ContentPart.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.clientToolResult !== undefined) {
      ClientToolResult.encode(message.clientToolResult, writer.uint32(42).fork()).join();
    }
    for (const v of message.consentGrants) {
      writer.uint32(50).string(v!);
    }
    if (message.duplexStart !== undefined) {
      DuplexStart.encode(message.duplexStart, writer.uint32(58).fork()).join();
    }
    if (message.audioInput !== undefined) {
      AudioInputChunk.encode(message.audioInput, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = ClientMessage_MetadataEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.metadata[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.parts.push(ContentPart.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientToolResult = ClientToolResult.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.consentGrants.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.duplexStart = DuplexStart.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.audioInput = AudioInputChunk.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientMessage {
    return {
      sessionId: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      parts: globalThis.Array.isArray(object?.parts) ? object.parts.map((e: any) => ContentPart.fromJSON(e)) : [],
      clientToolResult: isSet(object.client_tool_result)
        ? ClientToolResult.fromJSON(object.client_tool_result)
        : undefined,
      consentGrants: globalThis.Array.isArray(object?.consent_grants)
        ? object.consent_grants.map((e: any) => globalThis.String(e))
        : [],
      duplexStart: isSet(object.duplex_start) ? DuplexStart.fromJSON(object.duplex_start) : undefined,
      audioInput: isSet(object.audio_input) ? AudioInputChunk.fromJSON(object.audio_input) : undefined,
    };
  },

  toJSON(message: ClientMessage): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.session_id = message.sessionId;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.parts?.length) {
      obj.parts = message.parts.map((e) => ContentPart.toJSON(e));
    }
    if (message.clientToolResult !== undefined) {
      obj.client_tool_result = ClientToolResult.toJSON(message.clientToolResult);
    }
    if (message.consentGrants?.length) {
      obj.consent_grants = message.consentGrants;
    }
    if (message.duplexStart !== undefined) {
      obj.duplex_start = DuplexStart.toJSON(message.duplexStart);
    }
    if (message.audioInput !== undefined) {
      obj.audio_input = AudioInputChunk.toJSON(message.audioInput);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientMessage>, I>>(base?: I): ClientMessage {
    return ClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientMessage>, I>>(object: I): ClientMessage {
    const message = createBaseClientMessage();
    message.sessionId = object.sessionId ?? "";
    message.content = object.content ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.parts = object.parts?.map((e) => ContentPart.fromPartial(e)) || [];
    message.clientToolResult = (object.clientToolResult !== undefined && object.clientToolResult !== null)
      ? ClientToolResult.fromPartial(object.clientToolResult)
      : undefined;
    message.consentGrants = object.consentGrants?.map((e) => e) || [];
    message.duplexStart = (object.duplexStart !== undefined && object.duplexStart !== null)
      ? DuplexStart.fromPartial(object.duplexStart)
      : undefined;
    message.audioInput = (object.audioInput !== undefined && object.audioInput !== null)
      ? AudioInputChunk.fromPartial(object.audioInput)
      : undefined;
    return message;
  },
};

function createBaseClientMessage_MetadataEntry(): ClientMessage_MetadataEntry {
  return { key: "", value: "" };
}

export const ClientMessage_MetadataEntry: MessageFns<ClientMessage_MetadataEntry> = {
  encode(message: ClientMessage_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientMessage_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientMessage_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientMessage_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ClientMessage_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientMessage_MetadataEntry>, I>>(base?: I): ClientMessage_MetadataEntry {
    return ClientMessage_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientMessage_MetadataEntry>, I>>(object: I): ClientMessage_MetadataEntry {
    const message = createBaseClientMessage_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseClientToolResult(): ClientToolResult {
  return { callId: "", resultJson: "", isRejected: false, rejectionReason: "" };
}

export const ClientToolResult: MessageFns<ClientToolResult> = {
  encode(message: ClientToolResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callId !== "") {
      writer.uint32(10).string(message.callId);
    }
    if (message.resultJson !== "") {
      writer.uint32(18).string(message.resultJson);
    }
    if (message.isRejected !== false) {
      writer.uint32(24).bool(message.isRejected);
    }
    if (message.rejectionReason !== "") {
      writer.uint32(34).string(message.rejectionReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientToolResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientToolResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resultJson = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isRejected = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.rejectionReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientToolResult {
    return {
      callId: isSet(object.call_id) ? globalThis.String(object.call_id) : "",
      resultJson: isSet(object.result_json) ? globalThis.String(object.result_json) : "",
      isRejected: isSet(object.is_rejected) ? globalThis.Boolean(object.is_rejected) : false,
      rejectionReason: isSet(object.rejection_reason) ? globalThis.String(object.rejection_reason) : "",
    };
  },

  toJSON(message: ClientToolResult): unknown {
    const obj: any = {};
    if (message.callId !== "") {
      obj.call_id = message.callId;
    }
    if (message.resultJson !== "") {
      obj.result_json = message.resultJson;
    }
    if (message.isRejected !== false) {
      obj.is_rejected = message.isRejected;
    }
    if (message.rejectionReason !== "") {
      obj.rejection_reason = message.rejectionReason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientToolResult>, I>>(base?: I): ClientToolResult {
    return ClientToolResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientToolResult>, I>>(object: I): ClientToolResult {
    const message = createBaseClientToolResult();
    message.callId = object.callId ?? "";
    message.resultJson = object.resultJson ?? "";
    message.isRejected = object.isRejected ?? false;
    message.rejectionReason = object.rejectionReason ?? "";
    return message;
  },
};

function createBaseServerMessage(): ServerMessage {
  return { message: undefined };
}

export const ServerMessage: MessageFns<ServerMessage> = {
  encode(message: ServerMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.message?.$case) {
      case "chunk":
        Chunk.encode(message.message.chunk, writer.uint32(10).fork()).join();
        break;
      case "toolCall":
        ToolCall.encode(message.message.toolCall, writer.uint32(18).fork()).join();
        break;
      case "done":
        Done.encode(message.message.done, writer.uint32(34).fork()).join();
        break;
      case "error":
        Error.encode(message.message.error, writer.uint32(42).fork()).join();
        break;
      case "mediaChunk":
        MediaChunk.encode(message.message.mediaChunk, writer.uint32(50).fork()).join();
        break;
      case "interruption":
        Interruption.encode(message.message.interruption, writer.uint32(58).fork()).join();
        break;
      case "runtimeHello":
        RuntimeHello.encode(message.message.runtimeHello, writer.uint32(66).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = { $case: "chunk", chunk: Chunk.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = { $case: "toolCall", toolCall: ToolCall.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = { $case: "done", done: Done.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.message = { $case: "error", error: Error.decode(reader, reader.uint32()) };
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.message = { $case: "mediaChunk", mediaChunk: MediaChunk.decode(reader, reader.uint32()) };
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.message = { $case: "interruption", interruption: Interruption.decode(reader, reader.uint32()) };
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.message = { $case: "runtimeHello", runtimeHello: RuntimeHello.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerMessage {
    return {
      message: isSet(object.chunk)
        ? { $case: "chunk", chunk: Chunk.fromJSON(object.chunk) }
        : isSet(object.tool_call)
        ? { $case: "toolCall", toolCall: ToolCall.fromJSON(object.tool_call) }
        : isSet(object.done)
        ? { $case: "done", done: Done.fromJSON(object.done) }
        : isSet(object.error)
        ? { $case: "error", error: Error.fromJSON(object.error) }
        : isSet(object.media_chunk)
        ? { $case: "mediaChunk", mediaChunk: MediaChunk.fromJSON(object.media_chunk) }
        : isSet(object.interruption)
        ? { $case: "interruption", interruption: Interruption.fromJSON(object.interruption) }
        : isSet(object.runtime_hello)
        ? { $case: "runtimeHello", runtimeHello: RuntimeHello.fromJSON(object.runtime_hello) }
        : undefined,
    };
  },

  toJSON(message: ServerMessage): unknown {
    const obj: any = {};
    if (message.message?.$case === "chunk") {
      obj.chunk = Chunk.toJSON(message.message.chunk);
    } else if (message.message?.$case === "toolCall") {
      obj.tool_call = ToolCall.toJSON(message.message.toolCall);
    } else if (message.message?.$case === "done") {
      obj.done = Done.toJSON(message.message.done);
    } else if (message.message?.$case === "error") {
      obj.error = Error.toJSON(message.message.error);
    } else if (message.message?.$case === "mediaChunk") {
      obj.media_chunk = MediaChunk.toJSON(message.message.mediaChunk);
    } else if (message.message?.$case === "interruption") {
      obj.interruption = Interruption.toJSON(message.message.interruption);
    } else if (message.message?.$case === "runtimeHello") {
      obj.runtime_hello = RuntimeHello.toJSON(message.message.runtimeHello);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerMessage>, I>>(base?: I): ServerMessage {
    return ServerMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerMessage>, I>>(object: I): ServerMessage {
    const message = createBaseServerMessage();
    switch (object.message?.$case) {
      case "chunk": {
        if (object.message?.chunk !== undefined && object.message?.chunk !== null) {
          message.message = { $case: "chunk", chunk: Chunk.fromPartial(object.message.chunk) };
        }
        break;
      }
      case "toolCall": {
        if (object.message?.toolCall !== undefined && object.message?.toolCall !== null) {
          message.message = { $case: "toolCall", toolCall: ToolCall.fromPartial(object.message.toolCall) };
        }
        break;
      }
      case "done": {
        if (object.message?.done !== undefined && object.message?.done !== null) {
          message.message = { $case: "done", done: Done.fromPartial(object.message.done) };
        }
        break;
      }
      case "error": {
        if (object.message?.error !== undefined && object.message?.error !== null) {
          message.message = { $case: "error", error: Error.fromPartial(object.message.error) };
        }
        break;
      }
      case "mediaChunk": {
        if (object.message?.mediaChunk !== undefined && object.message?.mediaChunk !== null) {
          message.message = { $case: "mediaChunk", mediaChunk: MediaChunk.fromPartial(object.message.mediaChunk) };
        }
        break;
      }
      case "interruption": {
        if (object.message?.interruption !== undefined && object.message?.interruption !== null) {
          message.message = {
            $case: "interruption",
            interruption: Interruption.fromPartial(object.message.interruption),
          };
        }
        break;
      }
      case "runtimeHello": {
        if (object.message?.runtimeHello !== undefined && object.message?.runtimeHello !== null) {
          message.message = {
            $case: "runtimeHello",
            runtimeHello: RuntimeHello.fromPartial(object.message.runtimeHello),
          };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseChunk(): Chunk {
  return { content: "" };
}

export const Chunk: MessageFns<Chunk> = {
  encode(message: Chunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Chunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Chunk {
    return { content: isSet(object.content) ? globalThis.String(object.content) : "" };
  },

  toJSON(message: Chunk): unknown {
    const obj: any = {};
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Chunk>, I>>(base?: I): Chunk {
    return Chunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Chunk>, I>>(object: I): Chunk {
    const message = createBaseChunk();
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseToolCall(): ToolCall {
  return { id: "", name: "", argumentsJson: "", execution: 0, consentMessage: "", categories: [] };
}

export const ToolCall: MessageFns<ToolCall> = {
  encode(message: ToolCall, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.argumentsJson !== "") {
      writer.uint32(26).string(message.argumentsJson);
    }
    if (message.execution !== 0) {
      writer.uint32(32).int32(message.execution);
    }
    if (message.consentMessage !== "") {
      writer.uint32(42).string(message.consentMessage);
    }
    for (const v of message.categories) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCall {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCall();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.argumentsJson = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.execution = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.consentMessage = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.categories.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCall {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      argumentsJson: isSet(object.arguments_json) ? globalThis.String(object.arguments_json) : "",
      execution: isSet(object.execution) ? toolExecutionFromJSON(object.execution) : 0,
      consentMessage: isSet(object.consent_message) ? globalThis.String(object.consent_message) : "",
      categories: globalThis.Array.isArray(object?.categories)
        ? object.categories.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ToolCall): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.argumentsJson !== "") {
      obj.arguments_json = message.argumentsJson;
    }
    if (message.execution !== 0) {
      obj.execution = toolExecutionToJSON(message.execution);
    }
    if (message.consentMessage !== "") {
      obj.consent_message = message.consentMessage;
    }
    if (message.categories?.length) {
      obj.categories = message.categories;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCall>, I>>(base?: I): ToolCall {
    return ToolCall.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCall>, I>>(object: I): ToolCall {
    const message = createBaseToolCall();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.argumentsJson = object.argumentsJson ?? "";
    message.execution = object.execution ?? 0;
    message.consentMessage = object.consentMessage ?? "";
    message.categories = object.categories?.map((e) => e) || [];
    return message;
  },
};

function createBaseToolResult(): ToolResult {
  return { id: "", resultJson: "", isError: false };
}

export const ToolResult: MessageFns<ToolResult> = {
  encode(message: ToolResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.resultJson !== "") {
      writer.uint32(18).string(message.resultJson);
    }
    if (message.isError !== false) {
      writer.uint32(24).bool(message.isError);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resultJson = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isError = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolResult {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      resultJson: isSet(object.result_json) ? globalThis.String(object.result_json) : "",
      isError: isSet(object.is_error) ? globalThis.Boolean(object.is_error) : false,
    };
  },

  toJSON(message: ToolResult): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.resultJson !== "") {
      obj.result_json = message.resultJson;
    }
    if (message.isError !== false) {
      obj.is_error = message.isError;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolResult>, I>>(base?: I): ToolResult {
    return ToolResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolResult>, I>>(object: I): ToolResult {
    const message = createBaseToolResult();
    message.id = object.id ?? "";
    message.resultJson = object.resultJson ?? "";
    message.isError = object.isError ?? false;
    return message;
  },
};

function createBaseDone(): Done {
  return { finalContent: "", usage: undefined, parts: [] };
}

export const Done: MessageFns<Done> = {
  encode(message: Done, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.finalContent !== "") {
      writer.uint32(10).string(message.finalContent);
    }
    if (message.usage !== undefined) {
      Usage.encode(message.usage, writer.uint32(18).fork()).join();
    }
    for (const v of message.parts) {
      ContentPart.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Done {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.finalContent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.usage = Usage.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parts.push(ContentPart.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Done {
    return {
      finalContent: isSet(object.final_content) ? globalThis.String(object.final_content) : "",
      usage: isSet(object.usage) ? Usage.fromJSON(object.usage) : undefined,
      parts: globalThis.Array.isArray(object?.parts) ? object.parts.map((e: any) => ContentPart.fromJSON(e)) : [],
    };
  },

  toJSON(message: Done): unknown {
    const obj: any = {};
    if (message.finalContent !== "") {
      obj.final_content = message.finalContent;
    }
    if (message.usage !== undefined) {
      obj.usage = Usage.toJSON(message.usage);
    }
    if (message.parts?.length) {
      obj.parts = message.parts.map((e) => ContentPart.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Done>, I>>(base?: I): Done {
    return Done.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Done>, I>>(object: I): Done {
    const message = createBaseDone();
    message.finalContent = object.finalContent ?? "";
    message.usage = (object.usage !== undefined && object.usage !== null) ? Usage.fromPartial(object.usage) : undefined;
    message.parts = object.parts?.map((e) => ContentPart.fromPartial(e)) || [];
    return message;
  },
};

function createBaseContentPart(): ContentPart {
  return { type: "", text: "", media: undefined };
}

export const ContentPart: MessageFns<ContentPart> = {
  encode(message: ContentPart, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.media !== undefined) {
      MediaContent.encode(message.media, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContentPart {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContentPart();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.media = MediaContent.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContentPart {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      media: isSet(object.media) ? MediaContent.fromJSON(object.media) : undefined,
    };
  },

  toJSON(message: ContentPart): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.media !== undefined) {
      obj.media = MediaContent.toJSON(message.media);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContentPart>, I>>(base?: I): ContentPart {
    return ContentPart.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContentPart>, I>>(object: I): ContentPart {
    const message = createBaseContentPart();
    message.type = object.type ?? "";
    message.text = object.text ?? "";
    message.media = (object.media !== undefined && object.media !== null)
      ? MediaContent.fromPartial(object.media)
      : undefined;
    return message;
  },
};

function createBaseMediaContent(): MediaContent {
  return { data: "", url: "", mimeType: "", storageRef: "" };
}

export const MediaContent: MessageFns<MediaContent> = {
  encode(message: MediaContent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== "") {
      writer.uint32(10).string(message.data);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    if (message.mimeType !== "") {
      writer.uint32(26).string(message.mimeType);
    }
    if (message.storageRef !== "") {
      writer.uint32(34).string(message.storageRef);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaContent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaContent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mimeType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.storageRef = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaContent {
    return {
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      mimeType: isSet(object.mime_type) ? globalThis.String(object.mime_type) : "",
      storageRef: isSet(object.storage_ref) ? globalThis.String(object.storage_ref) : "",
    };
  },

  toJSON(message: MediaContent): unknown {
    const obj: any = {};
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.mimeType !== "") {
      obj.mime_type = message.mimeType;
    }
    if (message.storageRef !== "") {
      obj.storage_ref = message.storageRef;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaContent>, I>>(base?: I): MediaContent {
    return MediaContent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaContent>, I>>(object: I): MediaContent {
    const message = createBaseMediaContent();
    message.data = object.data ?? "";
    message.url = object.url ?? "";
    message.mimeType = object.mimeType ?? "";
    message.storageRef = object.storageRef ?? "";
    return message;
  },
};

function createBaseUsage(): Usage {
  return { inputTokens: 0, outputTokens: 0, costUsd: 0 };
}

export const Usage: MessageFns<Usage> = {
  encode(message: Usage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.inputTokens !== 0) {
      writer.uint32(8).int32(message.inputTokens);
    }
    if (message.outputTokens !== 0) {
      writer.uint32(16).int32(message.outputTokens);
    }
    if (message.costUsd !== 0) {
      writer.uint32(29).float(message.costUsd);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Usage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUsage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.inputTokens = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.outputTokens = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.costUsd = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Usage {
    return {
      inputTokens: isSet(object.input_tokens) ? globalThis.Number(object.input_tokens) : 0,
      outputTokens: isSet(object.output_tokens) ? globalThis.Number(object.output_tokens) : 0,
      costUsd: isSet(object.cost_usd) ? globalThis.Number(object.cost_usd) : 0,
    };
  },

  toJSON(message: Usage): unknown {
    const obj: any = {};
    if (message.inputTokens !== 0) {
      obj.input_tokens = Math.round(message.inputTokens);
    }
    if (message.outputTokens !== 0) {
      obj.output_tokens = Math.round(message.outputTokens);
    }
    if (message.costUsd !== 0) {
      obj.cost_usd = message.costUsd;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Usage>, I>>(base?: I): Usage {
    return Usage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Usage>, I>>(object: I): Usage {
    const message = createBaseUsage();
    message.inputTokens = object.inputTokens ?? 0;
    message.outputTokens = object.outputTokens ?? 0;
    message.costUsd = object.costUsd ?? 0;
    return message;
  },
};

function createBaseError(): Error {
  return { code: "", message: "" };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Error {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.code = object.code ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseInterruption(): Interruption {
  return {};
}

export const Interruption: MessageFns<Interruption> = {
  encode(_: Interruption, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Interruption {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInterruption();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Interruption {
    return {};
  },

  toJSON(_: Interruption): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Interruption>, I>>(base?: I): Interruption {
    return Interruption.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Interruption>, I>>(_: I): Interruption {
    const message = createBaseInterruption();
    return message;
  },
};

function createBaseMediaChunk(): MediaChunk {
  return { mediaId: "", sequence: 0, isLast: false, mimeType: "", data: new Uint8Array(0) };
}

export const MediaChunk: MessageFns<MediaChunk> = {
  encode(message: MediaChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mediaId !== "") {
      writer.uint32(10).string(message.mediaId);
    }
    if (message.sequence !== 0) {
      writer.uint32(16).int32(message.sequence);
    }
    if (message.isLast !== false) {
      writer.uint32(24).bool(message.isLast);
    }
    if (message.mimeType !== "") {
      writer.uint32(34).string(message.mimeType);
    }
    if (message.data.length !== 0) {
      writer.uint32(42).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mediaId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sequence = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isLast = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.mimeType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaChunk {
    return {
      mediaId: isSet(object.media_id) ? globalThis.String(object.media_id) : "",
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      isLast: isSet(object.is_last) ? globalThis.Boolean(object.is_last) : false,
      mimeType: isSet(object.mime_type) ? globalThis.String(object.mime_type) : "",
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    };
  },

  toJSON(message: MediaChunk): unknown {
    const obj: any = {};
    if (message.mediaId !== "") {
      obj.media_id = message.mediaId;
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.isLast !== false) {
      obj.is_last = message.isLast;
    }
    if (message.mimeType !== "") {
      obj.mime_type = message.mimeType;
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaChunk>, I>>(base?: I): MediaChunk {
    return MediaChunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaChunk>, I>>(object: I): MediaChunk {
    const message = createBaseMediaChunk();
    message.mediaId = object.mediaId ?? "";
    message.sequence = object.sequence ?? 0;
    message.isLast = object.isLast ?? false;
    message.mimeType = object.mimeType ?? "";
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseInvocationRequest(): InvocationRequest {
  return { inputJson: "", invocationId: "", metadata: {} };
}

export const InvocationRequest: MessageFns<InvocationRequest> = {
  encode(message: InvocationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.inputJson !== "") {
      writer.uint32(10).string(message.inputJson);
    }
    if (message.invocationId !== "") {
      writer.uint32(18).string(message.invocationId);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      InvocationRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvocationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvocationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.inputJson = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.invocationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = InvocationRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.metadata[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InvocationRequest {
    return {
      inputJson: isSet(object.input_json) ? globalThis.String(object.input_json) : "",
      invocationId: isSet(object.invocation_id) ? globalThis.String(object.invocation_id) : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: InvocationRequest): unknown {
    const obj: any = {};
    if (message.inputJson !== "") {
      obj.input_json = message.inputJson;
    }
    if (message.invocationId !== "") {
      obj.invocation_id = message.invocationId;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvocationRequest>, I>>(base?: I): InvocationRequest {
    return InvocationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvocationRequest>, I>>(object: I): InvocationRequest {
    const message = createBaseInvocationRequest();
    message.inputJson = object.inputJson ?? "";
    message.invocationId = object.invocationId ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseInvocationRequest_MetadataEntry(): InvocationRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const InvocationRequest_MetadataEntry: MessageFns<InvocationRequest_MetadataEntry> = {
  encode(message: InvocationRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvocationRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvocationRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InvocationRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: InvocationRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvocationRequest_MetadataEntry>, I>>(base?: I): InvocationRequest_MetadataEntry {
    return InvocationRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvocationRequest_MetadataEntry>, I>>(
    object: I,
  ): InvocationRequest_MetadataEntry {
    const message = createBaseInvocationRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseInvocationResponse(): InvocationResponse {
  return { outputJson: "", usage: undefined, durationMs: 0, invocationId: "" };
}

export const InvocationResponse: MessageFns<InvocationResponse> = {
  encode(message: InvocationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outputJson !== "") {
      writer.uint32(10).string(message.outputJson);
    }
    if (message.usage !== undefined) {
      Usage.encode(message.usage, writer.uint32(18).fork()).join();
    }
    if (message.durationMs !== 0) {
      writer.uint32(24).int32(message.durationMs);
    }
    if (message.invocationId !== "") {
      writer.uint32(34).string(message.invocationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvocationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvocationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outputJson = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.usage = Usage.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.durationMs = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.invocationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InvocationResponse {
    return {
      outputJson: isSet(object.output_json) ? globalThis.String(object.output_json) : "",
      usage: isSet(object.usage) ? Usage.fromJSON(object.usage) : undefined,
      durationMs: isSet(object.duration_ms) ? globalThis.Number(object.duration_ms) : 0,
      invocationId: isSet(object.invocation_id) ? globalThis.String(object.invocation_id) : "",
    };
  },

  toJSON(message: InvocationResponse): unknown {
    const obj: any = {};
    if (message.outputJson !== "") {
      obj.output_json = message.outputJson;
    }
    if (message.usage !== undefined) {
      obj.usage = Usage.toJSON(message.usage);
    }
    if (message.durationMs !== 0) {
      obj.duration_ms = Math.round(message.durationMs);
    }
    if (message.invocationId !== "") {
      obj.invocation_id = message.invocationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvocationResponse>, I>>(base?: I): InvocationResponse {
    return InvocationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvocationResponse>, I>>(object: I): InvocationResponse {
    const message = createBaseInvocationResponse();
    message.outputJson = object.outputJson ?? "";
    message.usage = (object.usage !== undefined && object.usage !== null) ? Usage.fromPartial(object.usage) : undefined;
    message.durationMs = object.durationMs ?? 0;
    message.invocationId = object.invocationId ?? "";
    return message;
  },
};

function createBaseHealthRequest(): HealthRequest {
  return {};
}

export const HealthRequest: MessageFns<HealthRequest> = {
  encode(_: HealthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHealthRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HealthRequest {
    return {};
  },

  toJSON(_: HealthRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HealthRequest>, I>>(base?: I): HealthRequest {
    return HealthRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HealthRequest>, I>>(_: I): HealthRequest {
    const message = createBaseHealthRequest();
    return message;
  },
};

function createBaseHealthResponse(): HealthResponse {
  return { healthy: false, status: "", contractVersion: "", capabilities: [] };
}

export const HealthResponse: MessageFns<HealthResponse> = {
  encode(message: HealthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.healthy !== false) {
      writer.uint32(8).bool(message.healthy);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.contractVersion !== "") {
      writer.uint32(26).string(message.contractVersion);
    }
    for (const v of message.capabilities) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHealthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.healthy = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contractVersion = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HealthResponse {
    return {
      healthy: isSet(object.healthy) ? globalThis.Boolean(object.healthy) : false,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      contractVersion: isSet(object.contract_version) ? globalThis.String(object.contract_version) : "",
      capabilities: globalThis.Array.isArray(object?.capabilities)
        ? object.capabilities.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: HealthResponse): unknown {
    const obj: any = {};
    if (message.healthy !== false) {
      obj.healthy = message.healthy;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.contractVersion !== "") {
      obj.contract_version = message.contractVersion;
    }
    if (message.capabilities?.length) {
      obj.capabilities = message.capabilities;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HealthResponse>, I>>(base?: I): HealthResponse {
    return HealthResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HealthResponse>, I>>(object: I): HealthResponse {
    const message = createBaseHealthResponse();
    message.healthy = object.healthy ?? false;
    message.status = object.status ?? "";
    message.contractVersion = object.contractVersion ?? "";
    message.capabilities = object.capabilities?.map((e) => e) || [];
    return message;
  },
};

function createBaseHasConversationRequest(): HasConversationRequest {
  return { sessionId: "" };
}

export const HasConversationRequest: MessageFns<HasConversationRequest> = {
  encode(message: HasConversationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasConversationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasConversationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HasConversationRequest {
    return { sessionId: isSet(object.session_id) ? globalThis.String(object.session_id) : "" };
  },

  toJSON(message: HasConversationRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.session_id = message.sessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HasConversationRequest>, I>>(base?: I): HasConversationRequest {
    return HasConversationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HasConversationRequest>, I>>(object: I): HasConversationRequest {
    const message = createBaseHasConversationRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseHasConversationResponse(): HasConversationResponse {
  return { state: 0, detail: "" };
}

export const HasConversationResponse: MessageFns<HasConversationResponse> = {
  encode(message: HasConversationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== 0) {
      writer.uint32(8).int32(message.state);
    }
    if (message.detail !== "") {
      writer.uint32(18).string(message.detail);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasConversationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasConversationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.detail = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HasConversationResponse {
    return {
      state: isSet(object.state) ? resumeStateFromJSON(object.state) : 0,
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
    };
  },

  toJSON(message: HasConversationResponse): unknown {
    const obj: any = {};
    if (message.state !== 0) {
      obj.state = resumeStateToJSON(message.state);
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HasConversationResponse>, I>>(base?: I): HasConversationResponse {
    return HasConversationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HasConversationResponse>, I>>(object: I): HasConversationResponse {
    const message = createBaseHasConversationResponse();
    message.state = object.state ?? 0;
    message.detail = object.detail ?? "";
    return message;
  },
};

function createBaseDuplexStart(): DuplexStart {
  return { codec: "", sampleRate: 0, channels: 0, systemInstruction: "" };
}

export const DuplexStart: MessageFns<DuplexStart> = {
  encode(message: DuplexStart, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.codec !== "") {
      writer.uint32(10).string(message.codec);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(16).int32(message.sampleRate);
    }
    if (message.channels !== 0) {
      writer.uint32(24).int32(message.channels);
    }
    if (message.systemInstruction !== "") {
      writer.uint32(34).string(message.systemInstruction);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DuplexStart {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDuplexStart();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.codec = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.channels = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.systemInstruction = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DuplexStart {
    return {
      codec: isSet(object.codec) ? globalThis.String(object.codec) : "",
      sampleRate: isSet(object.sample_rate) ? globalThis.Number(object.sample_rate) : 0,
      channels: isSet(object.channels) ? globalThis.Number(object.channels) : 0,
      systemInstruction: isSet(object.system_instruction) ? globalThis.String(object.system_instruction) : "",
    };
  },

  toJSON(message: DuplexStart): unknown {
    const obj: any = {};
    if (message.codec !== "") {
      obj.codec = message.codec;
    }
    if (message.sampleRate !== 0) {
      obj.sample_rate = Math.round(message.sampleRate);
    }
    if (message.channels !== 0) {
      obj.channels = Math.round(message.channels);
    }
    if (message.systemInstruction !== "") {
      obj.system_instruction = message.systemInstruction;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DuplexStart>, I>>(base?: I): DuplexStart {
    return DuplexStart.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DuplexStart>, I>>(object: I): DuplexStart {
    const message = createBaseDuplexStart();
    message.codec = object.codec ?? "";
    message.sampleRate = object.sampleRate ?? 0;
    message.channels = object.channels ?? 0;
    message.systemInstruction = object.systemInstruction ?? "";
    return message;
  },
};

function createBaseRuntimeHello(): RuntimeHello {
  return { capabilities: [], media: undefined };
}

export const RuntimeHello: MessageFns<RuntimeHello> = {
  encode(message: RuntimeHello, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.capabilities) {
      writer.uint32(10).string(v!);
    }
    if (message.media !== undefined) {
      MediaNegotiation.encode(message.media, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RuntimeHello {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRuntimeHello();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.media = MediaNegotiation.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RuntimeHello {
    return {
      capabilities: globalThis.Array.isArray(object?.capabilities)
        ? object.capabilities.map((e: any) => globalThis.String(e))
        : [],
      media: isSet(object.media) ? MediaNegotiation.fromJSON(object.media) : undefined,
    };
  },

  toJSON(message: RuntimeHello): unknown {
    const obj: any = {};
    if (message.capabilities?.length) {
      obj.capabilities = message.capabilities;
    }
    if (message.media !== undefined) {
      obj.media = MediaNegotiation.toJSON(message.media);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RuntimeHello>, I>>(base?: I): RuntimeHello {
    return RuntimeHello.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RuntimeHello>, I>>(object: I): RuntimeHello {
    const message = createBaseRuntimeHello();
    message.capabilities = object.capabilities?.map((e) => e) || [];
    message.media = (object.media !== undefined && object.media !== null)
      ? MediaNegotiation.fromPartial(object.media)
      : undefined;
    return message;
  },
};

function createBaseMediaNegotiation(): MediaNegotiation {
  return { codec: "", sampleRate: 0, channels: 0, frameRate: 0, resolution: 0 };
}

export const MediaNegotiation: MessageFns<MediaNegotiation> = {
  encode(message: MediaNegotiation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.codec !== "") {
      writer.uint32(10).string(message.codec);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(16).int32(message.sampleRate);
    }
    if (message.channels !== 0) {
      writer.uint32(24).int32(message.channels);
    }
    if (message.frameRate !== 0) {
      writer.uint32(32).int32(message.frameRate);
    }
    if (message.resolution !== 0) {
      writer.uint32(40).int32(message.resolution);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaNegotiation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaNegotiation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.codec = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.channels = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.frameRate = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.resolution = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaNegotiation {
    return {
      codec: isSet(object.codec) ? globalThis.String(object.codec) : "",
      sampleRate: isSet(object.sample_rate) ? globalThis.Number(object.sample_rate) : 0,
      channels: isSet(object.channels) ? globalThis.Number(object.channels) : 0,
      frameRate: isSet(object.frame_rate) ? globalThis.Number(object.frame_rate) : 0,
      resolution: isSet(object.resolution) ? globalThis.Number(object.resolution) : 0,
    };
  },

  toJSON(message: MediaNegotiation): unknown {
    const obj: any = {};
    if (message.codec !== "") {
      obj.codec = message.codec;
    }
    if (message.sampleRate !== 0) {
      obj.sample_rate = Math.round(message.sampleRate);
    }
    if (message.channels !== 0) {
      obj.channels = Math.round(message.channels);
    }
    if (message.frameRate !== 0) {
      obj.frame_rate = Math.round(message.frameRate);
    }
    if (message.resolution !== 0) {
      obj.resolution = Math.round(message.resolution);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaNegotiation>, I>>(base?: I): MediaNegotiation {
    return MediaNegotiation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaNegotiation>, I>>(object: I): MediaNegotiation {
    const message = createBaseMediaNegotiation();
    message.codec = object.codec ?? "";
    message.sampleRate = object.sampleRate ?? 0;
    message.channels = object.channels ?? 0;
    message.frameRate = object.frameRate ?? 0;
    message.resolution = object.resolution ?? 0;
    return message;
  },
};

function createBaseAudioInputChunk(): AudioInputChunk {
  return { data: new Uint8Array(0), sequence: 0, isLast: false };
}

export const AudioInputChunk: MessageFns<AudioInputChunk> = {
  encode(message: AudioInputChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    if (message.sequence !== 0) {
      writer.uint32(16).uint32(message.sequence);
    }
    if (message.isLast !== false) {
      writer.uint32(24).bool(message.isLast);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioInputChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioInputChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sequence = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isLast = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioInputChunk {
    return {
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      isLast: isSet(object.is_last) ? globalThis.Boolean(object.is_last) : false,
    };
  },

  toJSON(message: AudioInputChunk): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.isLast !== false) {
      obj.is_last = message.isLast;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioInputChunk>, I>>(base?: I): AudioInputChunk {
    return AudioInputChunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioInputChunk>, I>>(object: I): AudioInputChunk {
    const message = createBaseAudioInputChunk();
    message.data = object.data ?? new Uint8Array(0);
    message.sequence = object.sequence ?? 0;
    message.isLast = object.isLast ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
