// Copyright 2025 Altaira Labs
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: api/proto/tools/v1/tools.proto

package toolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolRequest contains the request to execute a tool.
type ToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tool_name identifies which tool to execute.
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// arguments_json contains the tool arguments as a JSON string.
	// The schema depends on the specific tool being invoked.
	ArgumentsJson string `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// metadata contains optional key-value pairs for additional context.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tools_v1_tools_proto_rawDescGZIP(), []int{0}
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ToolResponse contains the result of a tool execution.
type ToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result_json contains the tool result as a JSON string.
	ResultJson string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// is_error indicates whether the tool execution failed.
	IsError bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// error_message contains the error description if is_error is true.
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tools_v1_tools_proto_rawDescGZIP(), []int{1}
}

func (x *ToolResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ListToolsRequest is the request to list available tools.
type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tools_v1_tools_proto_rawDescGZIP(), []int{2}
}

// ListToolsResponse contains the list of available tools.
type ListToolsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tools is the list of available tools.
	Tools         []*ToolInfo `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tools_v1_tools_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolInfo describes a single tool.
type ToolInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier for this tool.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description describes what the tool does.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// input_schema is a JSON schema describing the tool's input parameters.
	InputSchema   string `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tools_v1_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_tools_v1_tools_proto_rawDescGZIP(), []int{4}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

var File_api_proto_tools_v1_tools_proto protoreflect.FileDescriptor

const file_api_proto_tools_v1_tools_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/tools/v1/tools.proto\x12\x0eomnia.tools.v1\"\xd5\x01\n" +
	"\vToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\x12E\n" +
	"\bmetadata\x18\x03 \x03(\v2).omnia.tools.v1.ToolRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\fToolResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x12\n" +
	"\x10ListToolsRequest\"C\n" +
	"\x11ListToolsResponse\x12.\n" +
	"\x05tools\x18\x01 \x03(\v2\x18.omnia.tools.v1.ToolInfoR\x05tools\"c\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\tR\vinputSchema2\xa5\x01\n" +
	"\vToolService\x12D\n" +
	"\aExecute\x12\x1b.omnia.tools.v1.ToolRequest\x1a\x1c.omnia.tools.v1.ToolResponse\x12P\n" +
	"\tListTools\x12 .omnia.tools.v1.ListToolsRequest\x1a!.omnia.tools.v1.ListToolsResponseB3Z1github.com/altairalabs/omnia/pkg/tools/v1;toolsv1b\x06proto3"

var (
	file_api_proto_tools_v1_tools_proto_rawDescOnce sync.Once
	file_api_proto_tools_v1_tools_proto_rawDescData []byte
)

func file_api_proto_tools_v1_tools_proto_rawDescGZIP() []byte {
	file_api_proto_tools_v1_tools_proto_rawDescOnce.Do(func() {
		file_api_proto_tools_v1_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tools_v1_tools_proto_rawDesc), len(file_api_proto_tools_v1_tools_proto_rawDesc)))
	})
	return file_api_proto_tools_v1_tools_proto_rawDescData
}

var file_api_proto_tools_v1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_tools_v1_tools_proto_goTypes = []any{
	(*ToolRequest)(nil),       // 0: omnia.tools.v1.ToolRequest
	(*ToolResponse)(nil),      // 1: omnia.tools.v1.ToolResponse
	(*ListToolsRequest)(nil),  // 2: omnia.tools.v1.ListToolsRequest
	(*ListToolsResponse)(nil), // 3: omnia.tools.v1.ListToolsResponse
	(*ToolInfo)(nil),          // 4: omnia.tools.v1.ToolInfo
	nil,                       // 5: omnia.tools.v1.ToolRequest.MetadataEntry
}
var file_api_proto_tools_v1_tools_proto_depIdxs = []int32{
	5, // 0: omnia.tools.v1.ToolRequest.metadata:type_name -> omnia.tools.v1.ToolRequest.MetadataEntry
	4, // 1: omnia.tools.v1.ListToolsResponse.tools:type_name -> omnia.tools.v1.ToolInfo
	0, // 2: omnia.tools.v1.ToolService.Execute:input_type -> omnia.tools.v1.ToolRequest
	2, // 3: omnia.tools.v1.ToolService.ListTools:input_type -> omnia.tools.v1.ListToolsRequest
	1, // 4: omnia.tools.v1.ToolService.Execute:output_type -> omnia.tools.v1.ToolResponse
	3, // 5: omnia.tools.v1.ToolService.ListTools:output_type -> omnia.tools.v1.ListToolsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_tools_v1_tools_proto_init() }
func file_api_proto_tools_v1_tools_proto_init() {
	if File_api_proto_tools_v1_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tools_v1_tools_proto_rawDesc), len(file_api_proto_tools_v1_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tools_v1_tools_proto_goTypes,
		DependencyIndexes: file_api_proto_tools_v1_tools_proto_depIdxs,
		MessageInfos:      file_api_proto_tools_v1_tools_proto_msgTypes,
	}.Build()
	File_api_proto_tools_v1_tools_proto = out.File
	file_api_proto_tools_v1_tools_proto_goTypes = nil
	file_api_proto_tools_v1_tools_proto_depIdxs = nil
}
