{{- if .Values.memoryApi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omnia.memoryApi.fullname" . }}
  labels:
    {{- include "omnia.memoryApi.labels" . | nindent 4 }}
  {{- with .Values.memoryApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
